import test from 'node:test';
import assert from 'node:assert/strict';
import {InterviewCapture} from './interview-capture.mjs';
class Track{constructor(kind){this.kind=kind;this.readyState='live';this.enabled=true;}stop(){this.readyState='ended';}}
class Stream{constructor(tracks){this.tracks=tracks;}getTracks(){return this.tracks;}getAudioTracks(){return this.tracks.filter(t=>t.kind==='audio');}getVideoTracks(){return this.tracks.filter(t=>t.kind==='video');}}
class Context{constructor(){this.sampleRate=16000;this.state='running';this.destination={};}async resume(){}async close(){this.state='closed';}createMediaStreamDestination(){return {stream:new Stream([new Track('audio')])};}createMediaStreamSource(){return {connect(){},disconnect(){}};}createMediaElementSource(){return {connect(){},disconnect(){}};}}
class Recorder{static isTypeSupported(){return true;}constructor(){this.state='inactive';}start(){this.state='recording';}pause(){this.state='paused';}resume(){this.state='recording';}stop(){this.state='inactive';this.ondataavailable({data:new Blob(['test media'])});queueMicrotask(()=>this.onstop());}}
function make(overrides={}){let serial=0;const calls=[];const tracks=[];const c=new InterviewCapture({api:async(path)=>{calls.push(path);return {id:'id-'+(++serial),max_bytes:10000,max_seconds:600};},upload:async()=>{},mediaDevices:{getUserMedia:async()=>{const pair=[new Track('audio'),new Track('video')];tracks.push(...pair);return new Stream(pair);}},Context,Recorder,Stream,...overrides});return {c,calls,tracks};}
test('pause while permission is pending cancels start and releases eventual tracks',async()=>{let resolve;const pair=[new Track('audio'),new Track('video')];const {c,calls}=make({mediaDevices:{getUserMedia:()=>new Promise(r=>resolve=r)}});const p=c.begin('a',true);c.pause();resolve(new Stream(pair));await assert.rejects(p,/cancelled/);assert.ok(pair.every(t=>t.readyState==='ended'));assert.equal(calls.length,0);});
test('cancelled slot allocation is marked incomplete and never starts recorder',async()=>{let release;const calls=[];const {c,tracks}=make({api:async path=>{calls.push(path);if(path.endsWith('/recording'))return new Promise(r=>release=r);return {};}});const p=c.begin('a',true);while(!release)await Promise.resolve();await c.stop();release({id:'slot',max_bytes:10000,max_seconds:600});await assert.rejects(p,/cancelled/);assert.ok(calls.includes('/recordings/slot/abort'));assert.ok(tracks.every(t=>t.readyState==='ended'));assert.equal(c.recorder,null);});
test('new segment after saved segment uses new state and releases previous media',async()=>{const {c,tracks}=make();await c.begin('a',true);const first=await c.stop();assert.equal(first.complete,true);await c.begin('a',true);assert.equal(c.bytes,0);assert.equal(c.state,'recording');const second=await c.stop();assert.equal(second.complete,true);assert.notEqual(first.id,second.id);assert.ok(tracks.every(t=>t.readyState==='ended'));});
test('microphone failure yields failed, never saved',async()=>{const {c,tracks}=make();await c.begin('a',true);tracks[0].onended();const result=await c.stop();assert.equal(result.complete,false);assert.equal(c.state,'failed');});
