import test from 'node:test';
import assert from 'node:assert/strict';
import {InterviewCapture} from './interview-capture.mjs';
class Track{constructor(kind){this.kind=kind;this.enabled=true;this.readyState='live';}stop(){this.readyState='ended';}}
class Stream{constructor(tracks){this.tracks=tracks;}getTracks(){return this.tracks;}getAudioTracks(){return this.tracks.filter(t=>t.kind==='audio');}getVideoTracks(){return this.tracks.filter(t=>t.kind==='video');}}
class Context{constructor(){this.sampleRate=16000;this.state='running';this.destination={speaker:true};this.connections=[];}async resume(){}async close(){this.state='closed';}createMediaStreamDestination(){return {stream:new Stream([new Track('audio')])};}source(){const connections=this.connections;return {connect:v=>connections.push(v),disconnect(){}};}createMediaStreamSource(){return this.source();}createMediaElementSource(){return this.source();}}
class Recorder{static isTypeSupported(){return true;}constructor(stream){this.stream=stream;this.state='inactive';}start(){this.state='recording';}pause(){this.state='paused';}resume(){this.state='recording';}stop(){this.state='inactive';this.ondataavailable({data:new Blob(['fake media'])});queueMicrotask(()=>this.onstop());}}
function setup(){const calls=[];const tracks=[new Track('audio'),new Track('video')];const c=new InterviewCapture({api:async(p,b)=>{calls.push([p,b]);return {id:'recording',max_bytes:10000,max_seconds:600};},upload:async(...args)=>calls.push(['upload',...args]),mediaDevices:{getUserMedia:async()=>new Stream(tracks)},Context,Recorder,Stream});return {c,calls,tracks};}
test('one capture spans questions and binds exact application',async()=>{const {c,calls}=setup();await c.begin('application-1',true);c.routeQuestion({});c.routeQuestion({});assert.equal(calls.filter(x=>x[0].includes('/recording')).length,1);const result=await c.stop();assert.equal(result.complete,true);assert.equal(calls[0][0],'/v2/applications/application-1/recording');assert.ok(calls.some(x=>x[0]==='/recordings/recording/finish'));});
test('pause disables both tracks and resume reuses recorder',async()=>{const {c,tracks,calls}=setup();await c.begin('application-1',true);const recorder=c.recorder;c.pause();assert.ok(tracks.every(t=>!t.enabled));c.resume();assert.ok(tracks.every(t=>t.enabled));assert.equal(c.recorder,recorder);await c.stop();assert.ok(tracks.every(t=>t.readyState==='ended'));});
test('question audio reaches recording and playback graph',async()=>{const {c}=setup();await c.begin('a',true);c.routeQuestion({});assert.ok(c.context.connections.includes(c.mix));assert.ok(c.context.connections.includes(c.context.destination));await c.stop();});
test('no devices requested without consent',async()=>{const {c}=setup();await assert.rejects(c.begin('a',false),/consent/);assert.equal(c.stream,undefined);});
test('late permission grant after stop releases tracks',async()=>{const {c,tracks}=setup();let release;c.mediaDevices.getUserMedia=()=>new Promise(r=>release=r);const start=c.begin('a',true);await c.stop();release(new Stream(tracks));await assert.rejects(start,/cancelled/);assert.ok(tracks.every(t=>t.readyState==='ended'));});
test('upload failure never reports recording as saved',async()=>{const {c}=setup();c.upload=async()=>{throw Error('network');};await c.begin('a',true);const result=await c.stop();assert.equal(result.complete,false);assert.equal(c.state,'failed');assert.ok(result.blob.size>0);});
