import React,{useState,useEffect} from 'react';
import '../RoleManager.css';
import './integrated-interview.css';
async function read(path){const r=await fetch('/api'+path,{credentials:'same-origin'});const d=await r.json();if(!r.ok)throw Error(d.error||'Review unavailable');return d;}
export default function InterviewReview(){
 const [data,setData]=useState(null),[report,setReport]=useState(null),[application,setApplication]=useState(null),[error,setError]=useState('');const aid=new URLSearchParams(location.search).get('application');
 useEffect(()=>{let active=true;(async()=>{try{if(!aid)throw Error('Open the review for a specific application.');const [recordings,evaluation,apps]=await Promise.all([read('/admin/applications/'+encodeURIComponent(aid)+'/recordings'),read('/admin/v2/reports/'+encodeURIComponent(aid)),read('/admin/applications')]);if(active){setData(recordings);setReport(evaluation);setApplication(apps.find(a=>a.id===aid));}}catch(e){if(active)setError(e.message);}})();return()=>{active=false;};},[aid]);
 return <main className="role-admin interview-review"><a href="/">← Recruiter workspace / log in</a><h1>Interview review</h1>{error&&<p role="alert" className="role-error">{error}</p>}{data&&<><h2>{data.candidate} · {data.role}</h2><p>ClickUp: {report?.sync_status}. Evidence is advisory; a person makes the hiring decision.</p><section className="role-editor"><h2>Recording</h2><p>Only this application’s recording segments appear here. Temporary files may disappear after server replacement; download promptly.</p>{!data.recordings.length&&<p>No temporary recording is available for this application.</p>}{data.recordings.map(r=><article key={r.id}><h3>Recorded {new Date(r.created_at).toLocaleString()}</h3><p>{r.status} · {(r.bytes/1048576).toFixed(1)} MB</p>{r.status==='ready'?<><video controls preload="metadata" src={'/api/recordings/'+r.id+'/media'}/><a href={'/api/recordings/'+r.id+'/media'} download>Download this recording segment</a></>:<p>Upload is incomplete. Do not treat this as a complete interview recording.</p>}</article>)}</section>
 <section className="role-editor"><h2>Evidence report</h2>{!report?.report?<p>Report pending.</p>:<><p>{report.report.summary}</p>{report.report.criteria?.map(c=><article key={c.name}><h3>{c.name}</h3><p>{c.reason}</p><blockquote>{c.evidence||'No evidence supplied'}</blockquote><p>Question: {c.source_id||'Not specified'} · Confidence: {c.confidence||'Not specified'} (model-assessed)</p></article>)}</>}</section>
 <section className="role-editor"><h2>Saved interview transcript</h2>{application?.answers?.map((a,i)=><article key={a.event_id||i}><p>{a.stage||'Interview'} · {a.kind||'Question'}</p><h3>{a.question}</h3><p>{a.answer}</p></article>)}</section></>}</main>;
}
