export function accountInfo(value){if(value?.role!=='candidate'||typeof value.email!=='string'||!['google','password'].includes(value.auth_method)||value.password_change_allowed!==(value.auth_method==='password'))throw Error('Account settings are unavailable. Please retry.');return {email:value.email,role:value.role,auth_method:value.auth_method,password_change_allowed:value.password_change_allowed};}
export function supportTickets(value){if(!Array.isArray(value))throw Error('Support inbox is unavailable.');return value.map(t=>{if(!t||!['id','subject','message','status','reply','created'].every(k=>typeof t[k]==='string'))throw Error('Support inbox is unavailable.');return Object.fromEntries(['id','subject','message','status','reply','created'].map(k=>[k,t[k]]));});}
export function passwordError(data){if(!data.current_password||data.current_password.length>128)return 'Enter your current password.';if(data.password.length<12||data.password.length>128)return 'Use a new password of 12–128 characters.';if(data.password!==data.confirm_password)return 'New passwords do not match.';return '';}
export async function accountRequest(path,{body,signal,fetcher=globalThis.fetch,timeoutMs=path==='/logout'?65000:15000}={}){
 if(!['/me','/workspace/candidate/account','/workspace/password','/workspace/support','/logout'].includes(path))throw Error('Unsupported account request.');
 const c=new AbortController(),abort=()=>c.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)c.abort();const timer=setTimeout(abort,timeoutMs);
 try{const r=await fetcher('/api'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',signal:c.signal,headers:{'X-Requested-With':'Flashspace',...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});
 if(!r.ok){const e=Error(r.status===401&&path==='/workspace/password'?'Current password was not accepted, or your session expired.':r.status===401?'Your session expired. Sign in again.':r.status===403?'This action is not allowed for this account.':r.status===409?'Your account changed. Refresh settings or sign in again before retrying.':r.status===429?'Too many attempts. Please wait before trying again.':'Request failed. Your unsaved input has been kept.');e.status=r.status;throw e;}
 try{return await r.json();}catch{throw Error('Could not confirm the response. Check the saved state before retrying.');}
 }catch(e){if(c.signal.aborted)throw Error(path==='/logout'?'Sign out is taking longer than expected. Wait a moment, refresh, and sign in again if needed.':body===undefined?'Loading timed out. Please retry.':'Could not confirm whether the request was saved. Check your inbox or sign-in state before retrying; your input is retained.');throw e;}
 finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}
}
