// Candidate Settings / Help only; existing recruiter UI and providers unchanged.
import React,{useEffect,useRef,useState} from 'react';
import {Home,Search,FileText,Mic,UserRound,Settings,LifeBuoy,LogOut} from 'lucide-react';
import {candidateIdentity} from './candidate-dashboard.mjs';
import {accountRequest,accountInfo,supportTickets,passwordError} from './account-client.mjs';
import '../generated/styles.css';import './workspace.css';import './candidate-dashboard.css';import './candidate-account.css';
const BASE='/candidate/workspace/';
const nav=[['Workspace',[['dashboard','Dashboard',Home],['jobs','Explore Jobs',Search],['applications','My Applications',FileText],['interviews','My Interviews',Mic],['profile','My Profile',UserRound]]],['Account',[['settings','Settings',Settings],['help','Help & Support',LifeBuoy]]]];
export default function CandidateAccount({page='settings'}){
 const help=page==='help',title=help?'Help & Support':'Settings';
 const [access,setAccess]=useState('checking'),[data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[actionError,setActionError]=useState('');
 const [password,setPassword]=useState({current_password:'',password:'',confirm_password:''}),[ticket,setTicket]=useState({subject:'',message:''});
 const mounted=useRef(false),locked=useRef(false),action=useRef(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;action.current?.abort();};},[]);
 useEffect(()=>{let alive=true;const c=new AbortController();setLoading(true);setData(null);setError('');async function load(){try{const u=await accountRequest('/me',{signal:c.signal});if(!alive)return;if(!candidateIdentity(u)){setAccess('denied');return;}setAccess('allowed');const result=await accountRequest(help?'/workspace/support':'/workspace/candidate/account',{signal:c.signal});const parsed=help?supportTickets(result):accountInfo(result);if(alive)setData(parsed);}catch(e){if(alive){setError(e.message);setAccess(a=>e.status===401||e.status===403?'denied':a==='allowed'?'allowed':'error');}}finally{if(alive)setLoading(false);}}load();return()=>{alive=false;c.abort();};},[revision,help]);
 async function work(fn){if(locked.current)return;locked.current=true;setBusy(true);setActionError('');setNotice('');action.current=new AbortController();try{await fn(action.current.signal);}catch(e){if(mounted.current)setActionError(e.message);}finally{locked.current=false;if(mounted.current)setBusy(false);}}
 function change(e){e.preventDefault();const invalid=passwordError(password);if(invalid){setActionError(invalid);return;}return work(async signal=>{const saved=await accountRequest('/workspace/password',{body:password,signal});if(saved?.ok!==true||saved.sign_in_required!==true)throw Error('Password change could not be confirmed. Try signing in again.');if(mounted.current){setPassword({current_password:'',password:'',confirm_password:''});window.location.assign('/candidate/login');}});}
 function send(e){e.preventDefault();if(ticket.subject.trim().length<3||ticket.message.trim().length<10){setActionError('Enter a subject of at least 3 characters and a message of at least 10 characters.');return;}return work(async signal=>{const saved=await accountRequest('/workspace/support',{body:ticket,signal});if(typeof saved?.id!=='string'||saved.status!=='open')throw Error('Request receipt could not be confirmed. Refresh your inbox before resending.');if(!mounted.current)return;setTicket({subject:'',message:''});setNotice('Request saved in your in-app support inbox. No email was sent.');setRevision(n=>n+1);});}
 const logout=()=>work(async signal=>{await accountRequest('/logout',{body:{},signal});if(mounted.current)window.location.assign('/candidate/login');});
 if(access!=='allowed')return <main className="cd-gate"><h1>{loading&&access==='checking'?'Checking your candidate account…':access==='denied'?'Candidate access required':title+' unavailable'}</h1>{error&&<p role="alert">{error}</p>}{!loading&&<><a href="/candidate/login">Sign in to your candidate account</a>{access==='error'&&<button onClick={()=>setRevision(n=>n+1)}>Try again</button>}</>}</main>;
 return <div className="tr-shell cd-shell ca-shell"><a className="cd-skip" href="#candidate-account-content">Skip to content</a><aside><a className="cd-brand" href={BASE+'dashboard'}><span className="cd-mark" aria-hidden="true"><svg width="26" height="26" viewBox="0 0 24 24">{[[2,7],[6,12],[10,17],[14,12],[18,7]].map(([x,h])=><rect key={x} x={x} y={(24-h)/2} width="2" height={h} rx="1" fill="currentColor"/>)}</svg></span><span>teamrecrut<small>BY STIRRING MINDS</small></span></a>{nav.map(([group,links])=><nav key={group} aria-label={group}><p className="cd-nav-label">{group}</p>{links.map(([id,label,Icon])=><a key={id} href={BASE+id} aria-current={id===page?'page':undefined}><Icon size={18} aria-hidden="true"/>{label}</a>)}</nav>)}<button className="cd-signout" disabled={busy} onClick={logout}><LogOut size={17}/>Sign out</button></aside><div className="tr-main"><header><span>Account / {title}</span><a href={BASE+'profile'}><UserRound size={17}/>My Profile</a></header><main id="candidate-account-content"><div className="cd-intro"><div><p className="tr-eyebrow">YOUR ACCOUNT</p><h1>{title}</h1><p>{help?'Get guidance and contact the hiring team through your private in-app inbox.':'Manage your sign-in and find your profile preferences.'}</p></div><button className="cd-refresh" disabled={busy||loading} onClick={()=>setRevision(n=>n+1)}>Refresh {help?'inbox':'settings'}</button></div>
 {loading&&<p role="status">Loading {help?'support requests':'settings'}…</p>}{error&&<div role="alert"><p>{error}</p><button onClick={()=>setRevision(n=>n+1)}>Try again</button></div>}{notice&&<p role="status" className="ca-notice">{notice}</p>}
 {!help&&data&&<><section className="ca-card"><h2>Account details</h2><label>Login email<input readOnly value={data.email}/></label><label>Account type<input readOnly value="Candidate"/></label><p>Sign-in method: {data.auth_method==='google'?'Google':'Email and password'}</p><p className="tr-note">Email and account type cannot be changed here.</p></section><section className="ca-card"><h2>Password and security</h2>{data.password_change_allowed?<form onSubmit={change} aria-label="Change password"><p>Changing your password signs out every existing session, including this one.</p>{[['current_password','Current password','current-password'],['password','New password','new-password'],['confirm_password','Confirm new password','new-password']].map(([key,label,autocomplete])=><label key={key}>{label}<input type="password" required maxLength={128} minLength={key==='current_password'?1:12} autoComplete={autocomplete} disabled={busy} value={password[key]} onChange={e=>setPassword({...password,[key]:e.target.value})}/></label>)}{actionError&&<p role="alert">{actionError}</p>}<div className="ca-actions"><button disabled={busy}>Change password and sign out</button><button type="button" className="ca-secondary" disabled={busy} onClick={()=>{setPassword({current_password:'',password:'',confirm_password:''});setActionError('');}}>Cancel</button></div></form>:<><p>This account uses Google sign-in. Manage your Google password through Google.</p><a href="https://myaccount.google.com/security" target="_blank" rel="noopener noreferrer">Open Google Account security</a>{actionError&&<p role="alert">{actionError}</p>}</>}<p className="tr-note">Forgot-password email delivery is not configured yet. No reset email can be requested here.</p></section><section className="ca-card"><h2>Profile, preferences and Resume</h2><p>Manage personal details, job preferences and your HTTPS resume link in one place.</p><a href={BASE+'profile'}>Edit My Profile →</a></section><section className="ca-card"><h2>Account and data requests</h2><p>Contact the hiring team through Help & Support. Requests are reviewed by a person; submitting one does not automatically delete or change your account.</p><a href={BASE+'help'}>Open Help & Support →</a></section></>}
 {help&&<><section className="ca-card"><h2>Common questions</h2>{[['How do I prepare for an interview?','Use the interview device checks, allow microphone access when requested, and listen to the test sound. The interview is voice-only; it begins after the required consent and one Begin action.'],['Where can I update my Resume?','Use the HTTPS resume link in My Profile. File upload is not available. Previously submitted applications retain their original links.'],['What if I cannot sign in?','Google accounts should use Google sign-in where configured. Forgot-password email setup is pending; do not share your password or API keys in a support request.'],['How do I request help with my data?','Submit a request below for human review. This does not automatically delete your account, profile or ClickUp records. Speech transcripts are retained with your application.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><section className="ca-card"><h2>New support request</h2><p className="tr-note">In-app support only. Include the affected page, approximate time and a short description. Do not include passwords, reset links, API keys or sensitive documents.</p><form onSubmit={send} aria-label="New support request"><label>Subject<input value={ticket.subject} required minLength={3} maxLength={150} disabled={busy} onChange={e=>setTicket({...ticket,subject:e.target.value})}/></label><label>Message<textarea rows={5} value={ticket.message} required minLength={10} maxLength={4000} disabled={busy} onChange={e=>setTicket({...ticket,message:e.target.value})}/></label>{actionError&&<p role="alert">{actionError}</p>}<button disabled={busy}>{busy?'Saving request…':'Send in-app request'}</button></form></section><section className="ca-card"><h2>Your requests</h2>{data?.length===0&&<p>No support requests yet.</p>}{data?.map(t=><article className="ca-ticket" key={t.id}><h3>{t.subject}</h3><p className="tr-note">{t.status==='resolved'?'Resolved':t.status==='open'?'Open':'Status unavailable'} · {Number.isFinite(Date.parse(t.created))?new Date(t.created).toLocaleString():'Date not recorded'}</p><p>{t.message}</p>{t.reply?<div className="ca-reply"><strong>Hiring team reply</strong><p>{t.reply}</p></div>:<p className="tr-note">No reply yet. Check this inbox for updates.</p>}</article>)}</section></>}
 </main></div></div>;
}
