// My Profile only. Existing free text preserved beside new structured entries.
import React,{useEffect,useRef,useState} from 'react';
import {Home,Search,FileText,Mic,UserRound,Settings,LifeBuoy,LogOut} from 'lucide-react';
import {candidateIdentity} from './candidate-dashboard.mjs';
import {SECTIONS,FIELDS,REPEAT,newEntry,safeHref,profileResponse,profileRequest} from './candidate-profile.mjs';
import '../generated/styles.css';import './workspace.css';import './candidate-dashboard.css';import './candidate-profile.css';
const BASE='/candidate/workspace/';
const navigation=[['Workspace',[['dashboard','Dashboard',Home],['jobs','Explore Jobs',Search],['applications','My Applications',FileText],['interviews','My Interviews',Mic],['profile','My Profile',UserRound],['resume','Resume',FileText]]],['Account',[['settings','Settings',Settings],['help','Help & Support',LifeBuoy]]]];
const clone=value=>JSON.parse(JSON.stringify(value));
function ReadFields({section,value}){return <dl className="cp-values">{FIELDS[section].map(([key,label,type])=>{const v=value[key];if(type==='checkbox')return v?<div key={key}><dt>{label}</dt><dd>Yes</dd></div>:null;return <div key={key}><dt>{label}</dt><dd>{v?(type==='url'&&safeHref(v)?<a href={safeHref(v)} target="_blank" rel="noopener noreferrer">{v}</a>:v):'Not provided'}</dd></div>;})}</dl>;}
function Inputs({section,value,onChange,prefix,disabled}){return <div className="cp-fields">{FIELDS[section].map(([key,label,type,max,required])=>{const id=prefix+'-'+key;const set=v=>onChange({...value,[key]:v,...(key==='current'&&v?{end:''}:{})});const props={id,'aria-label':label+(required?' *':''),value:value[key]||'',disabled:disabled||(key==='end'&&value.current),required:!!required,maxLength:max,onChange:e=>set(e.target.value)};return <label key={key} htmlFor={id} className={type==='textarea'?'cp-wide':type==='checkbox'?'cp-check':''}>{label}{required?' *':''}{type==='checkbox'?<input id={id} aria-label={label} type="checkbox" checked={!!value[key]} disabled={disabled} onChange={e=>set(e.target.checked)}/>:type==='textarea'?<textarea {...props} rows={4}/>:type==='select'?<select {...props}>{[['','Not specified'],['any','Any'],['remote','Remote'],['onsite','On-site'],['hybrid','Hybrid']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input {...props} type={type} pattern={section==='education'&&['start','end'].includes(key)||key==='year'?'[0-9]{4}':undefined}/>}</label>;})}</div>;}
export default function CandidateProfile(){
 const [access,setAccess]=useState('checking'),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[editing,setEditing]=useState(null),[draft,setDraft]=useState(null),[skill,setSkill]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[latest,setLatest]=useState(null);
 const mounted=useRef(false),locked=useRef(false),controller=useRef(null),draftBase=useRef(null);
 const dirty=!!editing&&JSON.stringify(draft)!==JSON.stringify(draftBase.current);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{let alive=true;const c=new AbortController();setLoading(true);setError('');async function load(){try{const user=await profileRequest('/me',{signal:c.signal});if(!alive)return;if(!candidateIdentity(user)){setAccess('denied');return;}setAccess('allowed');const data=profileResponse(await profileRequest('/workspace/candidate/profile',{signal:c.signal}));if(alive)setProfile(data);}catch(e){if(alive){setError(e.message);setAccess(a=>e.status===401||e.status===403?'denied':a==='allowed'?'allowed':'error');}}finally{if(alive)setLoading(false);}}load();return()=>{alive=false;c.abort();};},[revision]);
 useEffect(()=>{const before=e=>{if(dirty){e.preventDefault();e.returnValue='';}};const link=e=>{if(dirty&&e.target.closest('a[href]')&&!window.confirm('Leave this page and discard unsaved profile changes?')){e.preventDefault();e.stopPropagation();}};window.addEventListener('beforeunload',before);document.addEventListener('click',link,true);return()=>{window.removeEventListener('beforeunload',before);document.removeEventListener('click',link,true);};},[dirty]);
 function edit(section){if(busy)return;if(dirty&&!window.confirm('Discard unsaved changes and edit another section?'))return;const value=clone(profile.sections[section]);draftBase.current=clone(value);setDraft(value);setEditing(section);setSkill('');setError('');setNotice('');setConflict(false);setLatest(null);}
 function cancel(){if(dirty&&!window.confirm('Discard unsaved changes in this section?'))return;setEditing(null);setDraft(null);setSkill('');setConflict(false);setLatest(null);setError('');}
 async function work(fn){if(locked.current)return;locked.current=true;setBusy(true);setError('');controller.current=new AbortController();try{await fn(controller.current.signal);}catch(e){if(mounted.current){setError(e.message);if(e.status===409)setConflict(true);}}finally{locked.current=false;if(mounted.current)setBusy(false);}}
 function save(e){e.preventDefault();if(conflict)return;return work(async signal=>{const data=profileResponse(await profileRequest('/workspace/candidate/profile',{body:{version:profile.version,section:editing,value:draft},signal}));if(!mounted.current)return;setProfile(data);setEditing(null);setDraft(null);setNotice('Profile saved.');setLatest(null);});}
 const review=()=>work(async signal=>{const data=profileResponse(await profileRequest('/workspace/candidate/profile',{signal}));if(mounted.current)setLatest(data);});
 function useLatest(){if(!window.confirm('Replace your unsaved draft with the latest saved section?'))return;setProfile(latest);const v=clone(latest.sections[editing]);draftBase.current=clone(v);setDraft(v);setConflict(false);setLatest(null);setError('');}
 function addSkill(){const value=skill.trim();if(!value)return;if(value.length>80||draft.items.length>=40||draft.items.some(s=>s.toLowerCase()===value.toLowerCase())){setError('Use unique skills, up to 40 items and 80 characters each.');return;}setDraft({...draft,items:[...draft.items,value]});setSkill('');setError('');}
 const logout=()=>{if(dirty&&!window.confirm('Sign out and discard unsaved changes?'))return;work(async signal=>{await profileRequest('/logout',{body:{},signal});if(mounted.current){draftBase.current=draft;window.location.assign('/candidate/login');}});};
 if(access!=='allowed')return <main className="cd-gate"><h1>{loading&&access==='checking'?'Checking your candidate account…':access==='denied'?'Candidate access required':'My Profile unavailable'}</h1>{error&&<p role="alert">{error}</p>}{!loading&&<><a href="/candidate/login">Sign in to your candidate account</a>{access==='error'&&<button onClick={()=>setRevision(n=>n+1)}>Try again</button>}</>}</main>;
 return <div className="tr-shell cd-shell cp-shell"><a className="cd-skip" href="#candidate-profile-content">Skip to profile</a><aside><a className="cd-brand" href={BASE+'dashboard'}><span className="cd-mark" aria-hidden="true"><svg width="26" height="26" viewBox="0 0 24 24">{[[2,7],[6,12],[10,17],[14,12],[18,7]].map(([x,h])=><rect key={x} x={x} y={(24-h)/2} width="2" height={h} rx="1" fill="currentColor"/>)}</svg></span><span>teamrecrut<small>BY STIRRING MINDS</small></span></a>{navigation.map(([group,links])=><nav key={group} aria-label={group}><p className="cd-nav-label">{group}</p>{links.map(([id,label,Icon])=><a key={id} href={BASE+id} aria-current={id==='profile'?'page':undefined}><Icon size={18} aria-hidden="true"/>{label}{id==='resume'&&<small>Link only</small>}</a>)}</nav>)}<p className="cd-resume-note">Resume links are supported. File upload is not available yet.</p><button className="cd-signout" disabled={busy} onClick={logout}><LogOut size={17}/>Sign out</button></aside><div className="tr-main"><header><span><span className="cd-breadcrumb">Workspace / </span>My Profile</span><a href={BASE+'profile'}><UserRound size={17}/>My Profile</a></header><main id="candidate-profile-content" tabIndex={-1}><section className="cp-page"><div className="cd-intro"><div><p className="tr-eyebrow">YOUR STORY, IN YOUR WORDS</p><h1>My Profile</h1><p>Share your background, projects and the work you want to do next.</p></div><button className="cd-refresh" disabled={loading||busy||!!editing} onClick={()=>setRevision(n=>n+1)}>Refresh profile</button></div><p className="tr-note">All sections are optional except your name. Internships, freelance, volunteer and personal projects are welcome. This information is not a suitability score.</p>{loading&&<p role="status">Loading your profile…</p>}{notice&&<p role="status" className="cp-notice">{notice}</p>}{error&&!editing&&<div role="alert"><p>{error}</p><button onClick={()=>setRevision(n=>n+1)}>Try again</button></div>}
 {profile&&SECTIONS.map(([section,title])=>{const value=profile.sections[section],active=editing===section;return <section key={section} className="cp-card" aria-labelledby={'cp-title-'+section}><div className="cp-heading"><h2 id={'cp-title-'+section}>{title}</h2>{!active&&<button type="button" className="cp-edit" disabled={busy} onClick={()=>edit(section)}>Edit {title}</button>}</div>{section==='personal'&&<div className="cp-email"><label htmlFor="cp-login-email">Login email<input id="cp-login-email" aria-label="Login email" aria-describedby="cp-email-note" type="email" readOnly value={profile.email}/></label><small id="cp-email-note">Email and account type cannot be changed here.</small></div>}
 {profile.legacy[section]&&<details className="cp-legacy" open><summary>Previously saved {title.toLowerCase()} text</summary><p>{profile.legacy[section]}</p><small>Kept exactly as saved; not automatically split into entries. New entries below do not erase this text.</small></details>}
 {section==='resume'&&<p className="tr-note">HTTPS resume link only. File upload and private file storage are not available yet. Existing submitted applications retain their original resume link.</p>}{section==='links'&&<p className="tr-note">Links are optional. Their contents are not fetched or verified automatically.</p>}{section==='preferences'&&<p className="tr-note">Profile preferences only; recommendations remain based on roles you applied to.</p>}
 {active?<form onSubmit={save} aria-label={'Edit '+title} aria-busy={busy}>{REPEAT.includes(section)?<>{section==='experience'&&<label className="cp-check">No work experience yet<input type="checkbox" checked={draft.no_experience} disabled={busy||draft.items.length>0||!!profile.legacy.experience?.trim()} onChange={e=>setDraft({...draft,no_experience:e.target.checked})}/></label>}{draft.items.map((entry,i)=><fieldset key={i} className="cp-entry"><legend>{title} entry {i+1}</legend><Inputs section={section} value={entry} prefix={section+'-'+i} disabled={busy} onChange={next=>setDraft({...draft,items:draft.items.map((v,j)=>j===i?next:v)})}/><button type="button" className="cp-remove" disabled={busy} onClick={()=>{if(window.confirm('Remove this entry from the draft? It is only removed from your profile after Save.'))setDraft({...draft,items:draft.items.filter((_,j)=>j!==i)});}}>Remove entry {i+1}</button></fieldset>)}<button type="button" className="cp-add" disabled={busy||draft.items.length>=12||draft.no_experience} onClick={()=>setDraft({...draft,items:[...draft.items,newEntry(section)]})}>Add another {section==='certifications'?'certification':section==='projects'?'project':section==='education'?'education entry':'experience'}</button><small>Up to 12 entries. Required entry fields are marked *.</small></>:section==='skills'?<><div className="cp-tags">{draft.items.map((s,i)=><span key={s}>{s}<button type="button" aria-label={'Remove skill '+s} disabled={busy} onClick={()=>setDraft({items:draft.items.filter((_,j)=>j!==i)})}>×</button></span>)}</div><div className="cp-skill-add"><label>Add a skill<input value={skill} maxLength={80} disabled={busy} onChange={e=>setSkill(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSkill();}}}/></label><button type="button" disabled={busy} onClick={addSkill}>Add skill</button></div></>:<Inputs section={section} value={draft} prefix={section} disabled={busy} onChange={setDraft}/>}
 {error&&<p role="alert">{error}</p>}{conflict&&<div className="cp-conflict"><p>Your unsaved draft is still in the fields above. It will not overwrite the other session automatically.</p><button type="button" disabled={busy} onClick={review}>Review latest saved section</button>{latest&&<><pre>{JSON.stringify(latest.sections[section],null,2)}</pre><button type="button" disabled={busy} onClick={useLatest}>Use latest saved section</button></>}</div>}
 <div className="cp-actions"><button type="submit" disabled={busy||conflict}>{busy?'Saving…':'Save profile'}</button><button type="button" className="cp-cancel" disabled={busy} onClick={cancel}>Cancel</button>{dirty&&<span>Unsaved changes</span>}</div></form>:REPEAT.includes(section)?<>{value.no_experience&&<p>No work experience yet.</p>}{value.items.length?value.items.map((entry,i)=><div className="cp-entry" key={i}><h3>{title} entry {i+1}</h3><ReadFields section={section} value={entry}/></div>):!value.no_experience&&<p className="tr-note">No structured entries added yet.</p>}</>:section==='skills'?<div className="cp-tags">{value.items.length?value.items.map(s=><span key={s}>{s}</span>):<p className="tr-note">No skill tags added yet.</p>}</div>:<ReadFields section={section} value={value}/>}
 </section>;})}
 </section></main></div></div>;
}
