// Approved Explore Jobs route only. Reuse current Teamrecrut shell and modal vocabulary.
import React,{useEffect,useRef,useState} from 'react';
import {Home,Search,FileText,Mic,UserRound,Settings,LifeBuoy,LogOut,ArrowRight,Briefcase} from 'lucide-react';
import {Button,Badge,Dialog,DialogContent,DialogTitle,DialogDescription} from '@kits/shadcn-ui';
import CareersDialogs,{submitCareerApplication} from '../CareersDialogs';
import {candidateIdentity} from './candidate-dashboard.mjs';
import {FILTERS,display,publicRoles,filterValue,filterOptions,matches,existingDestination,jobsRequest} from './explore-jobs.mjs';
import '../generated/styles.css';
import './workspace.css';
import './candidate-dashboard.css';
import './explore-jobs.css';
const BASE='/candidate/workspace/';
const groups=[['Workspace',[['dashboard','Dashboard',Home],['jobs','Explore Jobs',Search],['applications','My Applications',FileText],['interviews','My Interviews',Mic],['profile','My Profile',UserRound],['resume','Resume',FileText]]],['Account',[['settings','Settings',Settings],['help','Help & Support',LifeBuoy]]]];
const go=path=>window.location.assign(path);
export default function ExploreJobs(){
 const [user,setUser]=useState(null),[access,setAccess]=useState('checking'),[roles,setRoles]=useState(null),[error,setError]=useState(''),[actionError,setActionError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 const [search,setSearch]=useState(''),[filters,setFilters]=useState({}),[selected,setSelected]=useState(null),[applyRole,setApplyRole]=useState(null),[busy,setBusy]=useState(false);
 const lock=useRef(false),mounted=useRef(false),actions=useRef(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;actions.current?.abort();};},[]);
 useEffect(()=>{let alive=true;const c=new AbortController();setLoading(true);setError('');setRoles(null);setSelected(null);setApplyRole(null);
  async function load(){try{const identity=await jobsRequest('/me',{signal:c.signal});if(!alive)return;if(!candidateIdentity(identity)){setAccess('denied');setUser(null);return;}setUser(identity);setAccess('allowed');const rows=publicRoles(await jobsRequest('/roles',{signal:c.signal}));if(alive)setRoles(rows);}
  catch(e){if(alive){setError(e.message);if(e.status===401||e.status===403){setUser(null);setAccess('denied');}else setAccess(current=>current==='allowed'?'allowed':'error');}}finally{if(alive)setLoading(false);}}
  load();return()=>{alive=false;c.abort();};
 },[revision]);
 function clear(){setSearch('');setFilters({});}
 async function action(work){if(lock.current)return;lock.current=true;setBusy(true);setActionError('');actions.current=new AbortController();try{await work(actions.current.signal);}catch(e){if(mounted.current)setActionError(e.message);}finally{lock.current=false;if(mounted.current)setBusy(false);}}
 function begin(role){return action(async signal=>{const dest=existingDestination(await jobsRequest('/applications',{signal}),role.id);if(!mounted.current)return;if(dest){go(dest);return;}setSelected(null);setApplyRole(role);});}
 function apply(e){e.preventDefault();const form=new FormData(e.currentTarget);return action(async signal=>{const aid=await submitCareerApplication(applyRole,form,async(url,options)=>{const data=await jobsRequest('/v2/applications',{body:JSON.parse(options.body),signal});return {ok:true,json:async()=>data};});if(mounted.current)go('/interview-v2?application='+encodeURIComponent(aid));});}
 const logout=()=>action(async signal=>{await jobsRequest('/logout',{body:{},signal});go('/candidate/login');});
 if(access!=='allowed')return <main className="cd-gate"><h1>{loading&&access==='checking'?'Checking your candidate account…':access==='denied'?'Candidate access required':'Explore Jobs unavailable'}</h1>{error&&<p role="alert">{error}</p>}{!loading&&<><a href="/candidate/login">Sign in to your candidate account</a>{access==='error'&&<button onClick={()=>setRevision(n=>n+1)}>Try again</button>}</>}</main>;
 const visible=roles?matches(roles,search,filters):[];
 return <div className="tr-shell cd-shell ej-shell"><a className="cd-skip" href="#explore-jobs-content">Skip to jobs</a><aside><a className="cd-brand" href={BASE+'dashboard'}><span className="cd-mark" aria-hidden="true"><svg width="26" height="26" viewBox="0 0 24 24">{[[2,7],[6,12],[10,17],[14,12],[18,7]].map(([x,h])=><rect key={x} x={x} y={(24-h)/2} width="2" height={h} rx="1" fill="currentColor"/>)}</svg></span><span>teamrecrut<small>BY STIRRING MINDS</small></span></a>{groups.map(([group,links])=><nav key={group} aria-label={group}><p className="cd-nav-label">{group}</p>{links.map(([id,label,Icon])=><a key={id} href={BASE+id} aria-current={id==='jobs'?'page':undefined}><Icon size={18} aria-hidden="true"/>{label}{id==='resume'&&<small>Link only</small>}</a>)}</nav>)}<p className="cd-resume-note">Resume links are supported. File upload is not available yet.</p><button className="cd-signout" disabled={busy} onClick={logout}><LogOut size={17}/>Sign out</button></aside>
 <div className="tr-main"><header><span><span className="cd-breadcrumb">Workspace / </span>Explore Jobs</span><a href={BASE+'profile'}><UserRound size={17}/>My Profile</a></header><main id="explore-jobs-content" tabIndex={-1}><section className="ej-page"><div className="cd-intro"><div><p className="tr-eyebrow">ROOM FOR YOUR AMBITION</p><h1>Find your next opportunity</h1><p>Explore current openings at Stirring Minds.</p></div><button className="cd-refresh" disabled={loading||busy} onClick={()=>setRevision(n=>n+1)}>Refresh jobs</button></div>
 <div className="ej-filters"><label className="ej-search">Search jobs, skills or keywords<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search jobs, skills or keywords"/></label><div className="ej-filter-grid">{FILTERS.map(([key,label])=><label key={key}>{label}<select disabled={!roles} value={filters[key]||''} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="">All {label.toLowerCase()}</option>{[...new Set([...(roles?filterOptions(roles,key):[]),...(filters[key]?[filters[key]]:[])])].map(value=><option key={value} value={value}>{value}</option>)}</select></label>)}</div><p className="tr-note">Filters use saved role values. Where work mode shares the location field, its original combined label is shown. Experience labels are not eligibility checks.</p><button className="ej-clear" onClick={clear}>Clear filters</button></div>
 {loading&&<p role="status">Loading open roles…</p>}{error&&<div role="alert"><p>{error}</p><button onClick={()=>setRevision(n=>n+1)}>Try again</button></div>}{actionError&&!selected&&!applyRole&&<p role="alert">{actionError}</p>}
 {roles&&<><p className="ej-count" role="status">{visible.length} {visible.length===1?'role':'roles'} found</p><div className="tr-job-grid">{visible.map(role=><article key={role.id}><p className="tr-eyebrow"><Briefcase size={16}/> {display(role.department)}</p><h2>{role.title}</h2><p className="ej-company">Stirring Minds</p><p>{display(role.location)} · {display(role.type)} · {display(role.experience)}</p><p>{display(role.description)}</p><div className="skills">{role.skills.map((s,i)=><span key={i}>{s}</span>)}</div><button disabled={busy} onClick={()=>{setActionError('');setSelected(role);}}>View role <ArrowRight size={16}/></button></article>)}</div>{!visible.length&&<div className="cd-empty"><h2>{roles.length?'No matching roles':'No open roles right now'}</h2><p>{roles.length?'Try another keyword or clear the filters to see all openings.':'Please check again later for Stirring Minds vacancies.'}</p>{roles.length>0&&<button onClick={clear}>Show all open roles</button>}</div>}</>}
 <Dialog open={!!selected} onOpenChange={open=>{if(!open&&!busy){setSelected(null);setActionError('');}}}><DialogContent className="ej-role-dialog"><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>Stirring Minds · {display(selected?.location)} · {display(selected?.type)} · {display(selected?.experience)}</DialogDescription>{selected&&<><Badge variant="secondary">Open role</Badge><dl className="ej-role-facts"><div><dt>Department</dt><dd>{display(selected.department)}</dd></div><div><dt>Work mode / saved location</dt><dd>{filterValue(selected,'work_mode')}</dd></div></dl><h3>Description</h3><p className="ej-saved-text">{display(selected.description)}</p><h3>What you’ll work on</h3><p className="ej-saved-text">{display(selected.details)}</p>{selected.responsibilities&&<><h3>Responsibilities</h3><p className="ej-saved-text">{selected.responsibilities}</p></>}{selected.requirements&&<><h3>Requirements</h3><p className="ej-saved-text">{selected.requirements}</p></>}<h3>Skills</h3><div className="skills">{selected.skills.length?selected.skills.map((s,i)=><span key={i}>{s}</span>):'Not specified'}</div><h3>Hiring process</h3><p className="ej-saved-text">{selected.hiring_process||'Apply with your profile, then join a two-stage AI interview. A person reviews your application.'}</p><p className="tr-note">Camera and microphone recording require separate consent and device checks before Begin.</p>{actionError&&<p role="alert">{actionError}</p>}<Button disabled={busy} onClick={()=>begin(selected)}>{busy?'Checking application…':'Apply for this role'}<ArrowRight/></Button></>}</DialogContent></Dialog>
 <CareersDialogs selected={null} setSelected={()=>{}} {...{applyRole,setApplyRole,user,busy,begin,apply}} error={actionError} setError={setActionError} auth={false}/>
 </section></main></div></div>;
}
