// Functional sidebar panels, preserving existing Teamrecrut design tokens.
import React,{useEffect,useState} from 'react';
const stageLabel=s=>s.replaceAll('_',' ');
function ErrorText({error}){return error?<p role="alert">{error}</p>:null;}
export function Settings({api,role}){
 const [saved,setSaved]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/workspace/settings').then(setSaved).catch(e=>setError(e.message));},[]);
 async function preferences(e){e.preventDefault();setBusy(true);setError('');try{setSaved(await api('/workspace/settings',saved));setNotice('Preferences saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function password(e){e.preventDefault();setBusy(true);setError('');try{await api('/workspace/password',Object.fromEntries(new FormData(e.currentTarget)));location.assign('/'+role+'/login');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><h1>Settings</h1><ErrorText error={error}/>{notice&&<p role="status">{notice}</p>}{role==='candidate'&&saved&&<form className="tr-profile" onSubmit={preferences}><h2>Job preferences</h2><label>Preferred location<input maxLength={200} value={saved.fields.preferred_location} onChange={e=>setSaved({...saved,fields:{...saved.fields,preferred_location:e.target.value}})}/></label><label>Preferred work mode<select value={saved.fields.work_mode} onChange={e=>setSaved({...saved,fields:{...saved.fields,work_mode:e.target.value}})}>{['any','remote','onsite','hybrid'].map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy}>Save preferences</button></form>}<form className="tr-profile" onSubmit={password}><h2>Change password</h2><p>Changing your password signs out every existing session, including this one.</p><label>Current password<input name="current_password" type="password" autoComplete="current-password" required maxLength={128}/></label><label>New password<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><label>Confirm new password<input name="confirm_password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><button disabled={busy}>Change password and sign out</button></form><h2>Privacy and account</h2><p>Email and role changes cannot be made through profile editing. MFA is not enabled for this initial release.</p><a href={'/'+role+'/workspace/help'}>Request help with your account or data →</a></section>;
}
export function Resume({api}){
 const [profile,setProfile]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/workspace/profile').then(setProfile).catch(e=>setError(e.message));},[]);
 async function save(e){e.preventDefault();setBusy(true);try{const p=await api('/workspace/profile',{version:profile.version,fields:{resume_url:profile.fields.resume_url}});setProfile(p);setNotice('Resume link saved. Existing applications keep the link originally submitted.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><h1>Resume</h1><p>Save an HTTPS link to a resume the hiring team can access. File uploads are not available in this branch yet.</p><ErrorText error={error}/>{notice&&<p role="status">{notice}</p>}{profile&&<form className="tr-profile" onSubmit={save}><label>Resume link<input type="url" maxLength={1000} value={profile.fields.resume_url} onChange={e=>setProfile({...profile,fields:{...profile.fields,resume_url:e.target.value}})}/></label><button disabled={busy}>Save resume link</button>{profile.fields.resume_url&&<a href={profile.fields.resume_url} target="_blank" rel="noopener noreferrer">Open saved resume →</a>}</form>}</section>;
}
export function Company({api}){
 const [record,setRecord]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/workspace/recruiter/company').then(setRecord).catch(e=>setError(e.message));},[]);
 async function save(e){e.preventDefault();setBusy(true);try{setRecord(await api('/workspace/recruiter/company',record));setNotice('Company profile saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><h1>Company</h1><p>This workspace belongs to Stirring Minds.</p><ErrorText error={error}/>{notice&&<p role="status">{notice}</p>}{record&&<form className="tr-profile" onSubmit={save}><label>Company name<input readOnly value={record.fields.name}/></label><label>Website<input type="url" maxLength={1000} value={record.fields.website} onChange={e=>setRecord({...record,fields:{...record.fields,website:e.target.value}})}/></label><label>About the company<textarea maxLength={4000} rows={6} value={record.fields.description} onChange={e=>setRecord({...record,fields:{...record.fields,description:e.target.value}})}/></label><button disabled={busy}>Save company profile</button></form>}</section>;
}
export function Pipeline({api,role,interviews=false}){
 const [items,setItems]=useState(null),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const endpoint='/workspace/'+role+'/applications';
 const load=()=>api(endpoint).then(setItems).catch(e=>setError(e.message));
 useEffect(()=>{load();},[endpoint]);
 async function move(a,e){e.preventDefault();const stage=new FormData(e.currentTarget).get('stage');if(!confirm('Record this recruiter decision: '+stageLabel(stage)+'?'))return;setBusy(true);setError('');try{await api('/workspace/recruiter/applications/'+a.id+'/stage',{version:a.version,stage});await load();setNotice('Hiring stage saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const visible=items?.filter(a=>filter==='all'||(interviews?a.interview_status:a.stage)===filter);
 return <section><h1>{interviews?(role==='candidate'?'My Interviews':'Interviews'):(role==='candidate'?'My Applications':'Applications')}</h1><ErrorText error={error}/>{notice&&<p role="status">{notice}</p>}<div className="tr-toolbar"><label>Filter<select value={filter} onChange={e=>setFilter(e.target.value)}>{['all',...(interviews?['interview','completed']:['applied','under_review','shortlisted','contacted','hired','rejected'])].map(s=><option key={s} value={s}>{stageLabel(s)}</option>)}</select></label><button onClick={load} disabled={busy}>Refresh</button></div>{visible?.map(a=><article className="tr-row" key={a.id}><div><h2>{a.role_title}</h2>{role==='recruiter'&&<p>{a.name}</p>}<p>Hiring: {stageLabel(a.stage)} · Interview: {a.interview_status==='completed'?'Completed':'In progress'}</p><p>Applied {new Date(a.created_at).toLocaleDateString()}</p><details><summary>Application timeline</summary><ul><li>Application submitted</li><li>Interview {a.interview_status==='completed'?'completed':'in progress'}</li>{a.events.map((e,i)=><li key={i}>{stageLabel(e.stage)} · {new Date(e.created).toLocaleString()}</li>)}</ul></details>{role==='recruiter'&&!interviews&&<form onSubmit={e=>move(a,e)} className="tr-toolbar"><label>Recruiter decision<select name="stage" defaultValue={a.stage}>{(a.interview_status==='completed'?['applied','under_review','shortlisted','contacted','hired','rejected']:['applied','rejected']).map(s=><option key={s} value={s}>{stageLabel(s)}</option>)}</select></label><button disabled={busy}>Save decision</button></form>}</div><a href={role==='recruiter'?'/interview-review?application='+encodeURIComponent(a.id):a.flow_version===2?'/interview-v2?application='+encodeURIComponent(a.id):'/candidate/workspace/legacy?application='+encodeURIComponent(a.id)}>{role==='recruiter'?'Review evidence':a.interview_status==='completed'?'View application':'Resume interview'} →</a></article>)}{items&&visible.length===0&&<p>No matching {interviews?'interviews':'applications'}.</p>}{!items&&!error&&<p>Loading…</p>}</section>;
}
export function Candidates({api}){
 const [items,setItems]=useState(null),[search,setSearch]=useState(''),[error,setError]=useState('');
 useEffect(()=>{api('/workspace/recruiter/candidates').then(setItems).catch(e=>setError(e.message));},[]);
 return <section><h1>Candidates</h1><p>People who applied to Stirring Minds roles. Decisions belong to each application.</p><label>Search name, email or skills<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><ErrorText error={error}/>{items?.filter(c=>(c.name+' '+c.email+' '+c.profile.skills).toLowerCase().includes(search.toLowerCase())).map(c=><article className="tr-row" key={c.id}><div><h2>{c.name}</h2><p>{c.email}</p><details><summary>Profile and applications</summary>{Object.entries(c.profile).filter(([k,v])=>v&&k!=='resume_url'&&k!=='name').map(([k,v])=><p key={k}><strong>{stageLabel(k)}:</strong> {v}</p>)}{c.profile.resume_url&&<a href={c.profile.resume_url} target="_blank" rel="noopener noreferrer">Open candidate resume</a>}<ul>{c.applications.map(a=><li key={a.id}><a href={'/interview-review?application='+encodeURIComponent(a.id)}>{a.role_title} · {stageLabel(a.stage)} → Review evidence</a></li>)}</ul></details></div></article>)}{items?.length===0&&<p>No candidates have applied yet.</p>}</section>;
}
export function Analytics({api}){
 const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{api('/workspace/recruiter/analytics').then(setData).catch(e=>setError(e.message));},[]);
 return <section><h1>Hiring overview</h1><p>Counts calculated from actual applications—not AI scores or rankings.</p><ErrorText error={error}/>{data&&<><dl className="tr-stats"><div><dt>Applications</dt><dd>{data.applications}</dd></div><div><dt>Completed interviews</dt><dd>{data.completed_interviews}</dd></div><div><dt>Interview completion</dt><dd>{data.completion_rate===null?'Not available':data.completion_rate+'%'}</dd></div></dl><h2>Current hiring stages</h2><dl className="tr-stats">{Object.entries(data.stages).map(([s,n])=><div key={s}><dt>{stageLabel(s)}</dt><dd>{n}</dd></div>)}</dl><h2>Applications per job</h2>{data.jobs.map(j=><article className="tr-row" key={j.title}><h3>{j.title}</h3><p>{j.applications} applications · {j.completed_interviews} completed interviews</p></article>)}{!data.jobs.length&&<p>No application data yet.</p>}</>}</section>;
}
export function Support({api,role}){
 const [tickets,setTickets]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api('/workspace/support').then(setTickets).catch(e=>setError(e.message));
 useEffect(()=>{load();},[]);
 async function submit(e){e.preventDefault();const form=e.currentTarget;setBusy(true);try{await api('/workspace/support',Object.fromEntries(new FormData(form)));form.reset();setNotice('Request saved in the in-app support inbox. No email was sent.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function reply(e,id){e.preventDefault();setBusy(true);try{await api('/workspace/recruiter/support/'+id,Object.fromEntries(new FormData(e.currentTarget)));setNotice('Reply saved. The candidate can read it here.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><h1>Help & Support</h1><details><summary>Interview and privacy help</summary><p>Use a supported browser, allow microphone/camera access only when requested, and check audio output. Applying does not begin recording: read consent and device checks before Begin.</p><p>Temporary interview recordings may disappear on server replacement. Saved application answers are stored separately. Use this inbox for account/data requests; do not include passwords or sensitive documents.</p></details><ErrorText error={error}/>{notice&&<p role="status">{notice}</p>}<form className="tr-profile" onSubmit={submit}><h2>New request</h2><label>Subject<input name="subject" required minLength={3} maxLength={150}/></label><label>Message<textarea name="message" required minLength={10} maxLength={4000}/></label><button disabled={busy}>Send in-app request</button></form><h2>{role==='recruiter'?'Support inbox':'Your requests'}</h2><button disabled={busy} onClick={load}>Refresh inbox</button>{tickets?.map(t=><article className="tr-row" key={t.id}><div><h3>{t.subject}</h3><p>{t.status} · {new Date(t.created).toLocaleString()}</p><p>{t.message}</p>{t.reply&&<p><strong>Reply:</strong> {t.reply}</p>}{role==='recruiter'&&<form className="tr-profile" onSubmit={e=>reply(e,t.id)}><label>Reply<textarea name="reply" defaultValue={t.reply} required maxLength={4000}/></label><label>Status<select name="status" defaultValue={t.status}><option>open</option><option>resolved</option></select></label><button disabled={busy}>Save reply</button></form>}</div></article>)}{tickets?.length===0&&<p>No support requests yet.</p>}</section>;
}
