// Approved My Applications page only. No application mutation or interview changes.
import React,{useEffect,useRef,useState} from 'react';
import {Home,Search,FileText,Mic,UserRound,Settings,LifeBuoy,LogOut,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,Button} from '@kits/shadcn-ui';
import {candidateIdentity} from './candidate-dashboard.mjs';
import {applicationsRequest,applicationsView,dateLabel,hiringLabel,interviewLabel,options,filterApplications,timeline,continuation} from './my-applications.mjs';
import '../generated/styles.css';
import './workspace.css';
import './candidate-dashboard.css';
import './my-applications.css';
const BASE='/candidate/workspace/';
const groups=[['Workspace',[['dashboard','Dashboard',Home],['jobs','Explore Jobs',Search],['applications','My Applications',FileText],['interviews','My Interviews',Mic],['profile','My Profile',UserRound],['resume','Resume',FileText]]],['Account',[['settings','Settings',Settings],['help','Help & Support',LifeBuoy]]]];
export default function MyApplications(){
 const [access,setAccess]=useState('checking'),[rows,setRows]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 const [search,setSearch]=useState(''),[hiring,setHiring]=useState(''),[interview,setInterview]=useState(''),[selectedId,setSelectedId]=useState(null),[busy,setBusy]=useState(false);
 const mounted=useRef(false),lock=useRef(false),actionController=useRef(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;actionController.current?.abort();};},[]);
 useEffect(()=>{let alive=true;const c=new AbortController();setLoading(true);setError('');setNotice('');setRows(null);setSelectedId(null);
  async function load(){try{const user=await applicationsRequest('/me',{signal:c.signal});if(!alive)return;if(!candidateIdentity(user)){setAccess('denied');return;}setAccess('allowed');const result=applicationsView(await applicationsRequest('/workspace/candidate/applications',{signal:c.signal}));if(alive)setRows(result);}
  catch(e){if(alive){setError(e.message);setAccess(current=>e.status===401||e.status===403?'denied':current==='allowed'?'allowed':'error');}}
  finally{if(alive)setLoading(false);}}
  load();return()=>{alive=false;c.abort();};
 },[revision]);
 async function action(work){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');actionController.current=new AbortController();try{await work(actionController.current.signal);}catch(e){if(mounted.current){setError(e.message);if(e.status===401||e.status===403){setRows(null);setSelectedId(null);setAccess('denied');}}}finally{lock.current=false;if(mounted.current)setBusy(false);}}
 function resume(id){return action(async signal=>{
  // Re-read ownership/status immediately before navigating, never restart a
  // completed interview from a stale application card or modal.
  const fresh=applicationsView(await applicationsRequest('/workspace/candidate/applications',{signal}));if(!mounted.current)return;setRows(fresh);
  const a=fresh.find(item=>item.id===id),destination=continuation(a);
  if(!a){setSelectedId(null);setNotice('This application is no longer available.');return;}
  if(!destination){setNotice('This application cannot be continued. Its latest status is shown.');return;}
  window.location.assign(destination);
 });}
 const logout=()=>action(async signal=>{await applicationsRequest('/logout',{signal});if(mounted.current)window.location.assign('/candidate/login');});
 function clear(){setSearch('');setHiring('');setInterview('');}
 const selected=rows?.find(a=>a.id===selectedId),history=selected?timeline(selected):null,visible=rows?filterApplications(rows,search,hiring,interview):[];
 if(access!=='allowed')return <main className="cd-gate"><h1>{loading&&access==='checking'?'Checking your candidate account…':access==='denied'?'Candidate access required':'My Applications unavailable'}</h1>{error&&<p role="alert">{error}</p>}{!loading&&<><a href="/candidate/login">Sign in to your candidate account</a>{access==='error'&&<button onClick={()=>setRevision(n=>n+1)}>Try again</button>}</>}</main>;
 return <div className="tr-shell cd-shell ma-shell"><a className="cd-skip" href="#my-applications-content">Skip to applications</a><aside><a className="cd-brand" href={BASE+'dashboard'}><span className="cd-mark" aria-hidden="true"><svg width="26" height="26" viewBox="0 0 24 24">{[[2,7],[6,12],[10,17],[14,12],[18,7]].map(([x,h])=><rect key={x} x={x} y={(24-h)/2} width="2" height={h} rx="1" fill="currentColor"/>)}</svg></span><span>teamrecrut<small>BY STIRRING MINDS</small></span></a>{groups.map(([group,links])=><nav key={group} aria-label={group}><p className="cd-nav-label">{group}</p>{links.map(([id,label,Icon])=><a key={id} href={BASE+id} aria-current={id==='applications'?'page':undefined}><Icon size={18} aria-hidden="true"/>{label}{id==='resume'&&<small>Link only</small>}</a>)}</nav>)}<p className="cd-resume-note">Resume links are supported. File upload is not available yet.</p><button className="cd-signout" disabled={busy} onClick={logout}><LogOut size={17} aria-hidden="true"/>Sign out</button></aside>
 <div className="tr-main"><header><span><span className="cd-breadcrumb">Workspace / </span>My Applications</span><a href={BASE+'profile'}><UserRound size={17} aria-hidden="true"/>My Profile</a></header><main id="my-applications-content" tabIndex={-1}><section className="ma-page"><div className="cd-intro"><div><p className="tr-eyebrow">YOUR NEXT CHAPTER</p><h1>My Applications</h1><p>Your submitted applications and their latest recorded statuses.</p></div><button className="cd-refresh" disabled={loading||busy} onClick={()=>setRevision(n=>n+1)}>Refresh applications</button></div>
 <div className="ma-filters"><label>Search by role<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search your applied roles"/></label><label htmlFor="ma-hiring">Hiring status<select id="ma-hiring" aria-label="Hiring status" value={hiring} onChange={e=>setHiring(e.target.value)} disabled={!rows}><option value="">All hiring statuses</option>{rows&&options(rows,'hiring').map(([key,label])=><option key={key} value={key}>{label}</option>)}{hiring&&rows&&!options(rows,'hiring').some(([key])=>key===hiring)&&<option value={hiring}>Previously selected status</option>}</select></label><label htmlFor="ma-interview">Interview status<select id="ma-interview" aria-label="Interview status" value={interview} onChange={e=>setInterview(e.target.value)} disabled={!rows}><option value="">All interview statuses</option>{rows&&options(rows,'interview').map(([key,label])=><option key={key} value={key}>{label}</option>)}{interview&&rows&&!options(rows,'interview').some(([key])=>key===interview)&&<option value={interview}>Previously selected status</option>}</select></label><button className="cd-refresh" onClick={clear}>Clear filters</button></div>
 {loading&&<p role="status">Loading your applications…</p>}{error&&!selected&&<div role="alert"><p>{error}</p><button disabled={busy||loading} onClick={()=>setRevision(n=>n+1)}>Try again</button></div>}{notice&&!selected&&<p role="status">{notice}</p>}
 {rows&&<><p className="ma-count" role="status">{visible.length} {visible.length===1?'application':'applications'} found · Newest first</p><div className="ma-list">{visible.map(a=><article className="ma-card" key={a.id}><div className="ma-card-main"><p className="tr-eyebrow">STIRRING MINDS</p><h2>{a.role_title}</h2><p>Applied {dateLabel(a.created_at)}</p><dl><div><dt>Hiring status</dt><dd>{hiringLabel(a)}</dd></div><div><dt>Interview status</dt><dd>{interviewLabel(a)}</dd></div></dl></div><div className="ma-actions"><button disabled={busy} onClick={()=>{setError('');setNotice('');setSelectedId(a.id);}}>View application</button>{continuation(a)&&<button className="ma-secondary" disabled={busy} onClick={()=>resume(a.id)}>Continue interview <ArrowRight size={16} aria-hidden="true"/></button>}</div></article>)}</div>{!visible.length&&<div className="cd-empty"><h2>{rows.length?'No matching applications':'No applications yet'}</h2><p>{rows.length?'Try another role or clear the filters.':'Once you apply to a Stirring Minds role, your application will appear here.'}</p>{rows.length?<button onClick={clear}>Show all applications</button>:<a href={BASE+'jobs'}>Explore Jobs →</a>}</div>}</>}
 <Dialog open={!!selected} onOpenChange={open=>{if(!open&&!busy){setSelectedId(null);setError('');setNotice('');}}}><DialogContent className="ma-dialog"><DialogTitle>{selected?.role_title}</DialogTitle><DialogDescription>Your application to Stirring Minds. Only saved events are shown.</DialogDescription>{selected&&<><dl className="ma-status"><div><dt>Hiring status</dt><dd>{hiringLabel(selected)}</dd></div><div><dt>Interview status</dt><dd>{interviewLabel(selected)}</dd></div></dl><h3>Recorded application history</h3><ol className="ma-timeline">{history.events.map((e,i)=><li key={i}><strong>{e.label}</strong><span>{dateLabel(e.date)}</span><p>{e.detail}</p></li>)}</ol>{history.completion&&<section className="ma-completion"><h3>{history.completion.label}</h3><p>{history.completion.detail}</p><p>Date not recorded</p></section>}<p className="tr-note">Interview and hiring statuses are separate. Awaiting recruiter review means queued for review, not proof that a recruiter has reviewed your application.</p>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{continuation(selected)&&<Button disabled={busy} onClick={()=>resume(selected.id)}>{busy?'Checking latest status…':'Continue interview'}<ArrowRight/></Button>}{selected.interview_status==='completed'&&<p>This interview is completed and cannot be restarted from this page.</p>}</>}</DialogContent></Dialog>
 </section></main></div></div>;
}
