// Candidate My Interviews only. No scheduling, capture or provider mutations.
import React,{useEffect,useRef,useState} from 'react';
import {Home,Search,FileText,Mic,UserRound,Settings,LifeBuoy,LogOut,ArrowRight} from 'lucide-react';
import {candidateIdentity} from './candidate-dashboard.mjs';
import {applicationsRequest,applicationsView,dateLabel,hiringLabel} from './my-applications.mjs';
import {interviewGroups,interviewAction,applicationLink} from './my-interviews.mjs';
import '../generated/styles.css';
import './workspace.css';
import './candidate-dashboard.css';
import './my-applications.css';
import './my-interviews.css';
const BASE='/candidate/workspace/';
const navigation=[['Workspace',[['dashboard','Dashboard',Home],['jobs','Explore Jobs',Search],['applications','My Applications',FileText],['interviews','My Interviews',Mic],['profile','My Profile',UserRound],['resume','Resume',FileText]]],['Account',[['settings','Settings',Settings],['help','Help & Support',LifeBuoy]]]];
export default function MyInterviews(){
 const [access,setAccess]=useState('checking'),[rows,setRows]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[search,setSearch]=useState(''),[busy,setBusy]=useState(false);
 const alive=useRef(false),locked=useRef(false),actionController=useRef(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;actionController.current?.abort();};},[]);
 useEffect(()=>{let current=true;const c=new AbortController();setLoading(true);setRows(null);setError('');setNotice('');
  async function load(){try{const identity=await applicationsRequest('/me',{signal:c.signal});if(!current)return;if(!candidateIdentity(identity)){setAccess('denied');return;}setAccess('allowed');const data=applicationsView(await applicationsRequest('/workspace/candidate/applications',{signal:c.signal}));if(current)setRows(data);}
  catch(e){if(current){setError(e.message);setAccess(a=>e.status===401||e.status===403?'denied':a==='allowed'?'allowed':'error');}}finally{if(current)setLoading(false);}}
  load();return()=>{current=false;c.abort();};
 },[revision]);
 async function action(work){if(locked.current)return;locked.current=true;setBusy(true);setError('');setNotice('');actionController.current=new AbortController();try{await work(actionController.current.signal);}catch(e){if(alive.current){setError(e.message);if(e.status===401||e.status===403){setRows(null);setAccess('denied');}}}finally{locked.current=false;if(alive.current)setBusy(false);}}
 function resume(id){return action(async signal=>{const fresh=applicationsView(await applicationsRequest('/workspace/candidate/applications',{signal}));if(!alive.current)return;setRows(fresh);const item=fresh.find(a=>a.id===id),destination=interviewAction(item);if(!destination){setNotice('This interview cannot be continued. Its latest status is shown.');return;}window.location.assign(destination);});}
 const logout=()=>action(async signal=>{await applicationsRequest('/logout',{signal});if(alive.current)window.location.assign('/candidate/login');});
 if(access!=='allowed')return <main className="cd-gate"><h1>{loading&&access==='checking'?'Checking your candidate account…':access==='denied'?'Candidate access required':'My Interviews unavailable'}</h1>{error&&<p role="alert">{error}</p>}{!loading&&<><a href="/candidate/login">Sign in to your candidate account</a>{access==='error'&&<button onClick={()=>setRevision(n=>n+1)}>Try again</button>}</>}</main>;
 const groups=rows?interviewGroups(rows,search):null;
 function card(a,completed){return <article className="ma-card" key={a.id}><div className="ma-card-main"><p className="tr-eyebrow">STIRRING MINDS · AI VOICE INTERVIEW</p><h3>{a.role_title}</h3><p className="mi-state">{completed?'Completed':'Available / In progress'}</p><p>Application date: {dateLabel(a.created_at)}</p><p>{completed?'Interview completion date: not recorded.':'No scheduled appointment date is provided by the current records.'}</p><p>Hiring status: {hiringLabel(a)}</p></div><div className="ma-actions">{!completed&&interviewAction(a)&&<button disabled={busy||loading} onClick={()=>resume(a.id)}>{busy?'Checking latest status…':'Open / Continue interview'}<ArrowRight size={16}/></button>}{!completed&&!interviewAction(a)&&<p className="tr-note">Continuation is unavailable for this application.</p>}<a className="mi-application" href={applicationLink(a)}>View application →</a></div></article>;}
 return <div className="tr-shell cd-shell mi-shell"><a className="cd-skip" href="#my-interviews-content">Skip to interviews</a><aside><a className="cd-brand" href={BASE+'dashboard'}><span className="cd-mark" aria-hidden="true"><svg width="26" height="26" viewBox="0 0 24 24">{[[2,7],[6,12],[10,17],[14,12],[18,7]].map(([x,h])=><rect key={x} x={x} y={(24-h)/2} width="2" height={h} rx="1" fill="currentColor"/>)}</svg></span><span>teamrecrut<small>BY STIRRING MINDS</small></span></a>{navigation.map(([group,links])=><nav key={group} aria-label={group}><p className="cd-nav-label">{group}</p>{links.map(([id,label,Icon])=><a key={id} href={BASE+id} aria-current={id==='interviews'?'page':undefined}><Icon size={18} aria-hidden="true"/>{label}{id==='resume'&&<small>Link only</small>}</a>)}</nav>)}<p className="cd-resume-note">Resume links are supported. File upload is not available yet.</p><button className="cd-signout" disabled={busy} onClick={logout}><LogOut size={17}/>Sign out</button></aside><div className="tr-main"><header><span><span className="cd-breadcrumb">Workspace / </span>My Interviews</span><a href={BASE+'profile'}><UserRound size={17}/>My Profile</a></header><main id="my-interviews-content" tabIndex={-1}><section className="mi-page"><div className="cd-intro"><div><p className="tr-eyebrow">YOUR CONVERSATIONS</p><h1>My Interviews</h1><p>Open an available interview or revisit a completed application.</p></div><button className="cd-refresh" disabled={loading||busy} onClick={()=>setRevision(n=>n+1)}>Refresh interviews</button></div><div className="ma-filters"><label>Search by role<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search your interview roles"/></label><button onClick={()=>setSearch('')}>Clear search</button></div>
 <p className="tr-note">Opening an interview takes you to its existing flow. Consent and device checks are required before Begin; opening this page does not start recording. Interview durations are not shown because they have not been measured.</p>
 {loading&&<p role="status">Loading your interviews…</p>}{error&&<div role="alert"><p>{error}</p><button disabled={busy||loading} onClick={()=>setRevision(n=>n+1)}>Try again</button></div>}{notice&&<p role="status">{notice}</p>}
 {groups&&<><section aria-labelledby="mi-active-title"><h2 id="mi-active-title">Available / In progress</h2><div className="ma-list">{groups.active.map(a=>card(a,false))}</div>{!groups.active.length&&<p>{search?'No matching unfinished interviews.':'No unfinished interviews.'}</p>}</section><section aria-labelledby="mi-completed-title"><h2 id="mi-completed-title">Completed</h2><div className="ma-list">{groups.completed.map(a=>card(a,true))}</div>{!groups.completed.length&&<p>{search?'No matching completed interviews.':'No completed interviews yet.'}</p>}</section>{groups.unknown.length>0&&<p>Some applications have an unrecognized interview status. <a href={BASE+'applications'}>Check My Applications</a> for their recorded details.</p>}{groups.total===0&&!search&&<div className="cd-empty"><h2>No interviews yet</h2><p>Apply to a Stirring Minds role to open its interview flow.</p><a href={BASE+'jobs'}>Explore Jobs →</a></div>}</>}
 </section></main></div></div>;
}
