// Teamrecrut role-first workspaces. Preserve the approved identity, not a redesign.
// Manrope headings/Hind UI; violet #7044dd, lilac #ece5ff, paper #faf9fd, ink #241c38.
// Public entry -> role-specific auth -> own workspace; profile stays top-right.
import React,{useEffect,useState} from 'react';
import CareersDialogs,{submitCareerApplication} from '../CareersDialogs';
import RoleManager from '../RoleManager';
import '../generated/styles.css';
import './workspace.css';

export async function request(path,body){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
 try{const r=await fetch('/api'+path,{signal:controller.signal,credentials:'same-origin',method:body===undefined?'GET':'POST',headers:{'X-Requested-With':'Flashspace',...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});const value=await r.json();if(!r.ok)throw Error(value.error||'Request failed. Please try again.');return value;}finally{clearTimeout(timer);}
}
const labels={name:'Full name',phone:'Phone number',summary:'Professional summary',education:'Education',experience:'Experience',skills:'Skills',projects:'Projects',certifications:'Certifications',preferences:'Job preferences',resume_url:'Resume link (HTTPS)',designation:'Designation',bio:'About you'};
const go=path=>window.location.assign(path);
function Brand(){return <a className="brand" href="/account-type">teamrecrut<span className="brand-sub">BY STIRRING MINDS</span></a>;}
function Auth({role,signup}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{await request('/auth/'+role+'/'+(signup?'signup':'login'),data);go('/'+role+'/workspace/dashboard');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="tr-auth"><Brand/><a href="/account-type">← Choose account type</a><section><p className="tr-eyebrow">{role==='candidate'?'YOUR NEXT CHAPTER':'STIRRING MINDS · AUTHORISED ACCESS'}</p><h1>{signup?'Create your candidate account':'Welcome back'}</h1><p>{role==='candidate'?'Sign in to continue your job search.':'Sign in to manage your hiring workspace.'}</p><form onSubmit={submit}>{signup&&<label>Full name<input name="name" required minLength={2} maxLength={100} autoComplete="name"/></label>}<label>{role==='recruiter'?'Work email':'Email address'}<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" required minLength={12} maxLength={128} autoComplete={signup?'new-password':'current-password'}/></label>{signup&&<label>Confirm password<input name="confirm_password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label>}{error&&<p role="alert">{error}</p>}<button disabled={busy}>{busy?'Please wait…':signup?'Create candidate account':'Sign in'}</button></form>{role==='candidate'&&<a href={signup?'/candidate/login':'/candidate/signup'}>{signup?'Already have an account? Sign in':'Create a candidate account'}</a>}{role==='recruiter'&&<p className="tr-note">Access is restricted to the authorised Stirring Minds recruiter. No public signup.</p>}</section></main>;
}
function Profile({onSaved}){
 const [profile,setProfile]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{request('/workspace/profile').then(setProfile).catch(e=>setError(e.message));},[]);
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setNotice('');setError('');try{const p=await request('/workspace/profile',{version:profile.version,fields:profile.fields});setProfile(p);setNotice('Profile saved.');onSaved(p);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><h1>My Profile</h1><p>Your details, kept with your account.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{profile?<form className="tr-profile" onSubmit={save}><label>Email<input readOnly value={profile.email}/><small>Email and account type cannot be changed here.</small></label>{Object.entries(profile.fields).map(([k,v])=><label key={k}>{labels[k]||k}{['name','phone','resume_url','designation'].includes(k)?<input value={v} type={k==='resume_url'?'url':'text'} required={k==='name'} onChange={e=>setProfile({...profile,fields:{...profile.fields,[k]:e.target.value}})}/>:<textarea rows={3} value={v} onChange={e=>setProfile({...profile,fields:{...profile.fields,[k]:e.target.value}})}/>}</label>)}<button disabled={busy}>{busy?'Saving…':'Save profile'}</button></form>:<p>Loading profile…</p>}</section>;
}
function Jobs({user,recommendations=false}){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[applyRole,setApplyRole]=useState(null),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{request(recommendations?'/workspace/candidate/recommendations':'/roles').then(r=>setItems(recommendations?r:r.map(role=>({role})))).catch(e=>setError(e.message)).finally(()=>setLoaded(true));},[recommendations]);
 async function begin(role){setSelected(null);try{const apps=await request('/applications');const a=apps.find(a=>a.role_id===role.id);if(a){go(a.flow_version===2?'/interview-v2?application='+encodeURIComponent(a.id):'/');return;}setApplyRole(role);}catch(e){setError(e.message);}}
 async function apply(e){e.preventDefault();if(busy)return;setBusy(true);try{const aid=await submitCareerApplication(applyRole,new FormData(e.currentTarget));go('/interview-v2?application='+encodeURIComponent(aid));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><h1>{recommendations?'Similar opportunities':'Explore jobs'}</h1><p>{recommendations?'Other Stirring Minds jobs related to roles you applied for.':'Find your next opportunity at Stirring Minds.'}</p><label>Search jobs or skills<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="tr-job-grid">{items.filter(({role:r})=>(r.title+' '+r.department+' '+r.skills.join(' ')).toLowerCase().includes(search.toLowerCase())).map(({role:r,reason})=><article key={r.id}><p className="tr-eyebrow">{r.department}</p><h2>{r.title}</h2><p>{r.location} · {r.type} · {r.experience}</p><p>{r.description}</p><div className="skills">{r.skills.map(s=><span key={s}>{s}</span>)}</div>{reason&&<p className="tr-note">{reason}</p>}<button onClick={()=>setSelected(r)}>View role →</button></article>)}</div>{loaded&&!items.length&&<p>{recommendations?'No similar opportunities yet. Recommendations appear when a published role shares skills or a department with your applications.':'No open roles at the moment.'}</p>}<CareersDialogs {...{selected,setSelected,applyRole,setApplyRole,user,busy,error,setError,begin,apply}} auth={false}/></section>;
}
function Applications({role,interviews=false}){
 const [apps,setApps]=useState(null),[error,setError]=useState('');
 useEffect(()=>{request(role==='candidate'?'/applications':'/admin/applications').then(setApps).catch(e=>setError(e.message));},[role]);
 return <section><h1>{interviews?'Interviews':'Applications'}</h1>{error&&<p role="alert">{error}</p>}{apps?.map(a=><article className="tr-row" key={a.id}><div><h2>{a.role_title}</h2>{role==='recruiter'&&<p>{a.name}</p>}<p>{a.status==='completed'?'Submitted for review':'Interview in progress'}</p></div><a href={role==='recruiter'?'/interview-review?application='+encodeURIComponent(a.id):a.flow_version===2?'/interview-v2?application='+encodeURIComponent(a.id):'/'}>{role==='recruiter'?'Review evidence':a.status==='completed'?'View interview':'Resume interview'} →</a></article>)}{apps?.length===0&&<p>No applications yet.</p>}{!apps&&!error&&<p>Loading applications…</p>}</section>;
}
function Dashboard({role,user}){
 const [apps,setApps]=useState(null),[jobs,setJobs]=useState(null),[error,setError]=useState('');
 useEffect(()=>{Promise.all([request(role==='candidate'?'/applications':'/admin/applications'),request(role==='candidate'?'/roles':'/admin/roles')]).then(([a,j])=>{setApps(a);setJobs(j);}).catch(e=>setError(e.message));},[role]);
 return <section><p className="tr-eyebrow">{role==='candidate'?'YOUR NEXT CHAPTER':'YOUR HIRING WORKSPACE'}</p><h1>Hello, {user.name}</h1><p>{role==='candidate'?'Your opportunities and conversations, in one place.':'Manage Stirring Minds roles and review interview evidence.'}</p>{error&&<p role="alert">{error}</p>}{apps&&<dl className="tr-stats"><div><dt>Applications</dt><dd>{apps.length}</dd></div><div><dt>Completed interviews</dt><dd>{apps.filter(a=>a.status==='completed').length}</dd></div><div><dt>{role==='candidate'?'Open roles':'Published jobs'}</dt><dd>{jobs.filter(r=>role==='candidate'||r.state==='published').length}</dd></div></dl>}<a href={'/'+role+'/workspace/'+(role==='candidate'?'jobs':'applications')}>{role==='candidate'?'Explore opportunities':'Review applications'} →</a>{role==='candidate'&&<Jobs user={user} recommendations/>}</section>;
}
export default function Workspace(){
 const path=location.pathname.replace(/\/$/,''),role=path.startsWith('/recruiter/')?'recruiter':'candidate';
 const [user,setUser]=useState(undefined),[error,setError]=useState('');
 useEffect(()=>{if(path.includes('/workspace/'))request('/me').then(setUser).catch(e=>{setError(e.message);setUser(null);});},[path]);
 if(path==='/account-type')return <main className="tr-entry"><Brand/><h1>How would you like to continue?</h1><p>Choose your Teamrecrut workspace.</p><div><a href="/candidate/login"><h2>Candidate</h2><p>Explore jobs, apply and meet your AI interviewer.</p><strong>Continue as Candidate →</strong></a><a href="/recruiter/login"><h2>Recruiter</h2><p>Authorised Stirring Minds hiring access.</p><strong>Continue as Recruiter →</strong></a></div><a href="/">Explore public roles</a></main>;
 if(path.endsWith('/login')||path==='/candidate/signup')return <Auth role={role} signup={path.endsWith('/signup')}/>;
 if(!path.includes('/workspace/'))return <main className="tr-entry"><h1>Page not found</h1><a href="/account-type">Choose account type</a></main>;
 if(user===undefined)return <main className="tr-entry">Checking your account…</main>;
 if(!user||user.role!==role)return <main className="tr-entry"><h1>{role==='candidate'?'Candidate':'Recruiter'} access required</h1>{error&&<p role="alert">{error}</p>}<a href={'/'+role+'/login'}>Sign in to this workspace</a></main>;
 const page=path.split('/').pop(),base='/'+role+'/workspace/';
 const nav=role==='candidate'?[['dashboard','Dashboard'],['jobs','Explore Jobs'],['applications','My Applications'],['interviews','My Interviews']]:[['dashboard','Dashboard'],['jobs','Jobs'],['applications','Applications'],['interviews','Interviews']];
 async function logout(){try{await request('/logout',{});go('/account-type');}catch(e){setError(e.message);}}
 return <div className="tr-shell"><aside><Brand/><p className="tr-eyebrow">{role.toUpperCase()} WORKSPACE</p><nav>{nav.map(([id,name])=><a key={id} href={base+id} aria-current={id===page?'page':undefined}>{name}</a>)}</nav><button onClick={logout}>Sign out</button></aside><div className="tr-main"><header><span>Stirring Minds</span><a href={base+'profile'}>My Profile</a></header>{error&&<p role="alert">{error}</p>}<main>{page==='profile'?<Profile onSaved={p=>setUser({...user,name:p.fields.name})}/>:page==='dashboard'?<Dashboard {...{role,user}}/>:page==='jobs'?role==='candidate'?<Jobs user={user}/>:<RoleManager/>:['applications','interviews'].includes(page)?<Applications role={role} interviews={page==='interviews'}/>:<section><h1>Page not found</h1><a href={base+'dashboard'}>Return to dashboard</a></section>}</main></div></div>;
}
