// Flashspace careers: preserve existing roles/recruiter workflow; new interviews
// enter the integrated v2 room. Existing v1 records remain on their legacy flow.
// Design: Manrope/Hind, paper #faf9fd, ink #241c38, lilac #ece5ff, violet #7044dd.
import React, { useEffect, useState } from "react";
import { ArrowUpRight, ArrowRight, BriefcaseBusiness, FileText, AudioLines, Settings2, LogOut, Search, MapPin, Clock3, ChevronRight, Volume2, ShieldCheck, Zap, Users, Code2, TrendingUp, RotateCw, Headphones, CircleHelp } from "lucide-react";
import { Button, Badge, Input, ToggleGroup, ToggleGroupItem, Alert, AlertDescription, Toaster } from "@kits/shadcn-ui";
import { toast } from "sonner";
import { api, LIVE, DEMO_ROLES, DEMO_APPLICANTS } from "./generated/api";
import { Wave, Interview, Dialogs } from "./generated/components";
import CareersDialogs, {submitCareerApplication} from "./CareersDialogs";
import "./generated/styles.css";
const icons={growth:TrendingUp,community:Users,engineering:Code2};
// Mark: four voices, and one that stands out of them. The outer bars are a
// spoken waveform - this product's premise is that a candidate is heard rather
// than read, and the hero animates the same motif - while the lime figure is
// the standout among them, which is what recruiting actually is. It degrades
// honestly: below ~24px the head and body merge into a single accent bar
// rather than turning to mush. Counter-skewed so the figure stands upright
// inside the tile's lean.
const MARK_BARS=[[1.6,7.6],[5.8,12],[15.8,13],[20,7.2]];
function Brandmark(){
 return <svg className="brandmark-wave" width="23" height="23" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
  {MARK_BARS.map(([x,h])=><rect key={x} x={x} y={(24-h)/2} width="2.6" height={h} rx="1.3" fill="currentColor"/>)}
  <circle className="mark-accent" cx="12" cy="4.5" r="2.6" fill="currentColor"/>
  <rect className="mark-accent" x="10.4" y="8.9" width="3.2" height="11.6" rx="1.6" fill="currentColor"/>
 </svg>;
}
function Brand(){return <div className="brand"><span className="brandmark"><Brandmark/></span><span>teamrecrut<span className="brand-sub">BY STIRRING MINDS</span></span></div>;}
export default function App(){
 const [page,setPage]=useState("roles"),[roles,setRoles]=useState(LIVE?[]:DEMO_ROLES),[user,setUser]=useState(null),[applications,setApplications]=useState([]),[adminApps,setAdminApps]=useState(LIVE?[]:DEMO_APPLICANTS);
 const [auth,setAuth]=useState(false),[register,setRegister]=useState(false),[selected,setSelected]=useState(null),[applyRole,setApplyRole]=useState(null),[active,setActive]=useState(null),[report,setReport]=useState(null),[practice,setPractice]=useState(false),[pendingRole,setPendingRole]=useState(null);
 const [filter,setFilter]=useState("All roles"),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[help,setHelp]=useState(false),[loaded,setLoaded]=useState(!LIVE);
 async function refresh(){const apps=await api.apps();setApplications(apps);return apps;}
 useEffect(()=>{document.getElementById("root")?.scrollTo({top:0});window.scrollTo(0,0);},[page]);
 useEffect(()=>{let mounted=true;(async()=>{try{const r=await api.roles();if(mounted)setRoles(r);const u=await api.me();if(mounted)setUser(u);if(u){const a=await api.apps();if(mounted)setApplications(a);}}catch(e){if(mounted)setError(e.message);}finally{if(mounted)setLoaded(true);}})();return()=>{mounted=false;};},[]);
 async function go(p){setPage(p);if(p==="applications"&&user)try{await refresh();}catch(e){toast.error(e.message);}if(p==="recruiter"&&(!LIVE||user?.admin))try{setAdminApps(await api.adminApps());}catch(e){toast.error(e.message);}}
 function openApplication(a){if(a.flow_version===2){window.location.assign('/interview-v2?application='+encodeURIComponent(a.id));return;}if(a.status==='completed'){setReport(a);setPage('applications');}else{setActive(a);setPage('interview');}}
 async function startRole(role){const existing=(await api.apps()).find(a=>a.role_id===role.id);if(existing){openApplication(existing);return;}setError('');setApplyRole(role);}
 function begin(role){setSelected(null);if(LIVE){if(user){startRole(role).catch(e=>toast.error(e.message));}else{setPendingRole(role);setRegister(true);setAuth(true);}return;}setApplyRole(role);if(!user){setRegister(true);setAuth(true);}}
 async function authenticate(e){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);try{const u=await api.auth(Object.fromEntries(fd),register);setUser(u);setAuth(false);await refresh();if(LIVE&&pendingRole){const role=pendingRole;setPendingRole(null);await startRole(role);return;}if(page==="recruiter"&&u.admin)setAdminApps(await api.adminApps());toast.success(LIVE?"You’re signed in":"Preview session started");}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function apply(e){e.preventDefault();if(busy)return;setBusy(true);setError("");const form=new FormData(e.currentTarget);try{if(LIVE){const aid=await submitCareerApplication(applyRole,form);setApplyRole(null);window.location.assign('/interview-v2?application='+encodeURIComponent(aid));return;}const a=await api.apply({...Object.fromEntries(form),role_id:applyRole.id,consent:true});await refresh();setApplyRole(null);openApplication(a);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const visible=roles.filter(r=>(filter==="All roles"||r.department===filter)&&`${r.title} ${r.description} ${r.skills.join(" ")}`.toLowerCase().includes(search.toLowerCase()));
 const departments=["All roles",...new Set(roles.map(r=>r.department))],isRecruiter=["recruiter","settings"].includes(page);
 return <div className="app-shell"><Toaster richColors position="top-right"/>
 <aside className="sidebar"><Brand/><div className="portal-label">YOUR NEXT CHAPTER</div><nav aria-label="Main navigation">{[["roles",BriefcaseBusiness,"Explore roles"],["applications",FileText,"My applications"]].map(([id,Icon,label])=><button key={id} className={page===id?"nav-link selected":"nav-link"} onClick={()=>go(id)}><Icon size={19}/>{label}{id==="applications"&&applications.length>0&&<span className="nav-count">{applications.length}</span>}</button>)}<button className="nav-link" onClick={()=>setPractice(true)}><AudioLines size={19}/>Interview practice<span className="tiny-dot"/></button></nav>
 <div className="sidebar-note"><span className="note-icon"><Headphones size={21}/></span><h3>Be heard.<br/>Not just read.</h3><p>A conversation about what you can do.</p><button className="text-link" onClick={()=>setHelp(true)}>How it works <ArrowUpRight size={16}/></button></div>
 <div className="side-bottom"><button className={isRecruiter?"nav-link selected":"nav-link"} onClick={()=>go("recruiter")}><Users size={18}/>Recruiter workspace<ArrowUpRight size={15}/></button>{LIVE&&user?.admin&&<a className="nav-link" href="/recruiter/roles"><BriefcaseBusiness size={18}/>Manage roles<ArrowUpRight size={15}/></a>}<button className="nav-link" onClick={()=>setHelp(true)}><CircleHelp size={18}/>Help & privacy</button><div className="side-footer">A little ambition goes a long way.</div></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb">Stirring Minds <ChevronRight size={15}/><strong>{isRecruiter?"Recruitment":"Careers"}</strong></div><div className="top-actions">{!LIVE&&<Badge variant="secondary">Interactive preview</Badge>}{user?<><span className="signed-name">{user.name}</span><Button variant="ghost" size="icon" aria-label="Sign out" onClick={async()=>{try{await api.logout();setUser(null);setApplications([]);setPage("roles");setActive(null);setPendingRole(null);}catch(e){toast.error(e.message);}}}><LogOut/></Button></>:<Button variant="outline" onClick={()=>{setRegister(false);setError("");setAuth(true);}}>Log in <ArrowUpRight/></Button>}</div></header><main>
 {page==="roles"&&<><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> SMALL TEAMS. BIG POSSIBILITIES.</div><h1>Your next move.<br/><span>Make it matter.</span></h1><p>Bring your ideas. Find your people.<br/>Build what’s next with Stirring Minds · Flashspace.</p><div className="hero-actions"><Button onClick={()=>document.getElementById("open-roles")?.scrollIntoView({behavior:"smooth"})}>Find your role <ArrowRight/></Button><button className="text-link" onClick={()=>setPractice(true)}><Volume2 size={18}/>Try an interview</button></div></div><div className="hero-art"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="voice-caption"><span className="status-dot"/> MORE THAN A RESUME</div><div className="voice-sculpture"><Wave active/></div><div className="voice-pill"><AudioLines size={21}/><span>Your voice. Your potential.</span><span className="play-dot"><ArrowUpRight size={18}/></span></div><div className="art-star">✳</div></div></section>
 <section className="process-strip" aria-label="Application process"><span><span className="step-num">1</span>Find your fit</span><ChevronRight/><span><span className="step-num">2</span>Tell us about yourself</span><ChevronRight/><span><span className="step-num">3</span>Meet your AI interviewer</span><div className="human-note"><ShieldCheck size={18}/>People make the final call.</div></section>
 <section id="open-roles" className="roles-section"><div className="section-heading"><div><div className="eyebrow">ROOM FOR YOUR AMBITION</div><h2>Find your kind of work <span className="count">{roles.length}</span></h2></div><div className="search-field"><Search size={18}/><Input aria-label="Search roles" placeholder="Search roles or skills" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="filter-row"><ToggleGroup type="single" value={filter} onValueChange={v=>v&&setFilter(v)} aria-label="Filter department">{departments.map(d=><ToggleGroupItem key={d} value={d}>{d}</ToggleGroupItem>)}</ToggleGroup>{!LIVE&&<span className="muted">Sample roles for this preview</span>}</div>
 {error&&<Alert><AlertDescription>{error}</AlertDescription></Alert>}<div className="role-grid">{visible.map((r,i)=>{const Icon=icons[r.id]||BriefcaseBusiness;return <article className="role-card" key={r.id}><div className="role-top"><span className={["role-icon color-0","role-icon color-1","role-icon color-2"][i%3]}><Icon size={25}/></span><Badge variant="outline">{r.department}</Badge></div><h3>{r.title}</h3><div className="role-meta"><span><MapPin size={15}/>{r.location}</span><span><Clock3 size={15}/>{r.type}</span></div><p>{r.description}</p><div className="skills">{r.skills.map(s=><span key={s}>{s}</span>)}</div><div className="role-bottom"><span>{r.experience}</span><button className="text-link" onClick={()=>setSelected(r)}>View role <ArrowUpRight size={18}/></button></div></article>;})}</div>
 {loaded&&visible.length===0&&<div className="empty-panel"><Search size={30}/><h3>{roles.length?"No matching roles":"New opportunities are on their way"}</h3><p>{roles.length?"Try a different skill or department.":"The team hasn’t published a role yet."}</p>{roles.length>0&&<Button variant="outline" onClick={()=>{setSearch("");setFilter("All roles");}}>Clear filters</Button>}</div>}{!loaded&&<p>Loading opportunities…</p>}</section><footer className="page-footer"><Brand/><span>Different strengths. Shared ambition.</span><button className="text-link" onClick={()=>setHelp(true)}>Privacy & your data <ArrowUpRight size={15}/></button></footer></>}
 {page==="applications"&&<section className="subpage"><div className="eyebrow">YOUR NEXT CHAPTER</div><h1>My applications</h1><p className="lead">Your progress, all in one place.</p>{!user?<div className="empty-panel"><FileText size={32}/><h3>Your next chapter starts here.</h3><p>Sign in to see and resume your applications.</p><Button onClick={()=>{setRegister(false);setAuth(true);}}>Log in <ArrowRight/></Button></div>:applications.length===0?<div className="empty-panel"><BriefcaseBusiness size={32}/><h3>Let’s find your first opportunity.</h3><p>You haven’t applied to a role yet.</p><Button onClick={()=>go("roles")}>Explore roles <ArrowRight/></Button></div>:<div className="application-stack">{applications.map(a=><article className="application-row" key={a.id}><div><Badge variant="secondary">{a.status==="completed"?"Submitted for review":"Interview in progress"}</Badge><h3>{a.role_title}</h3><p>{a.answers.length}{a.flow_version===2?'':' of 4'} answers saved · {new Date(a.created_at).toLocaleDateString()}</p></div><Button variant={a.status==="completed"?"outline":"default"} onClick={()=>openApplication(a)}>{a.status==="completed"?"View application":"Resume interview"}<ArrowRight/></Button></article>)}</div>}</section>}
 {page==="interview"&&active&&<Interview application={active} onSaved={async a=>{setActive(a);await refresh();}} onComplete={async a=>{setActive(null);await refresh();setPage("applications");setReport(a);}} onBack={()=>go("applications")}/>}
 {page==="recruiter"&&<section className="subpage"><div className="workspace-heading"><div><div className="eyebrow">THE PEOPLE BEHIND THE POTENTIAL</div><h1>Recruiter workspace</h1><p className="lead">Every conversation, with evidence to review.</p></div><div style={{display:'flex',gap:12,flexWrap:'wrap'}}>{LIVE&&user?.admin&&<Button asChild><a href="/recruiter/roles">Manage roles <BriefcaseBusiness/></a></Button>}<Button variant="outline" onClick={()=>go("settings")}><Settings2/>Integration setup</Button></div></div>{LIVE&&!user?.admin?<div className="empty-panel"><ShieldCheck size={32}/><h3>Recruiter access only</h3><p>Sign in with the admin account configured on Render.</p><Button onClick={()=>{setRegister(false);setAuth(true);}}>Recruiter login</Button></div>:<>{!LIVE&&<Alert><AlertDescription>Fictional sample candidates. Scores illustrate the layout, not a real evaluation. No ClickUp data is loaded or changed.</AlertDescription></Alert>}<div className="recruiter-toolbar"><h3>{adminApps.length} applications</h3><Button variant="ghost" onClick={async()=>{try{setAdminApps(await api.adminApps());toast.success("Applications refreshed");}catch(e){toast.error(e.message);}}}><RotateCw/>Refresh</Button></div><div className="candidate-table"><div className="candidate-head"><span>Candidate / role</span><span>Interview evaluation</span><span>ClickUp sync</span><span>Report</span></div>{adminApps.map(a=><button className="candidate-row" key={a.id} onClick={()=>a.flow_version===2?window.location.assign('/interview-review?application='+encodeURIComponent(a.id)):setReport({...a,recruiter:true})}><div className="candidate-name"><span className="initials">{a.name.slice(0,1)}</span><span><strong>{a.name}</strong><small>{a.role_title}</small></span></div><span className="score-text">{a.evaluation?.scoring_status==='not_scored'?'Evidence review':a.evaluation?.score??"Pending"}{a.evaluation?.score!=null&&<small>/100</small>}</span><Badge variant="secondary">{a.sync_status}</Badge><span className="text-link">Review <ArrowUpRight size={17}/></span></button>)}</div>{!adminApps.length&&<div className="empty-panel"><Users/><h3>No applications yet</h3><p>Publish an approved role, then test its mapped interview.</p></div>}</>}</section>}
 {page==="settings"&&<section className="subpage"><button className="text-link" onClick={()=>go("recruiter")}>← Back to recruitment</button><h1 className="mt-6">Connected by design.</h1><p className="lead">The website handles the conversation. ClickUp holds the candidate record.</p><div className="integration-flow"><div><BriefcaseBusiness/><strong>Role</strong><span>A List in your hiring Folder</span></div><ArrowRight/><div><Users/><strong>Application</strong><span>One candidate task per role</span></div><ArrowRight/><div><FileText/><strong>Interview report</strong><span>Summary, transcript & evidence</span></div></div><Alert><AlertDescription>{LIVE?"Staging only. Render Free can sleep; temporary videos can disappear after server replacement. Download recordings promptly. Accounts and submitted answers persist in PostgreSQL.":"Preview only: external services are not connected."}</AlertDescription></Alert><div className="setup-grid"><article><h3><Zap size={20}/>Render + Sarvam</h3><p>Render hosts the website, PostgreSQL stores progress, and Sarvam supplies transcription, questions and voice. V2 uses generic and domain question banks with bounded follow-ups.</p><p>Configure credentials only in Render environment settings. Recording consent is requested inside the interview.</p></article><article><h3><ShieldCheck size={20}/>Human-led hiring</h3><p>AI reports provide evidence for human review, not automatic hiring decisions. Video is for authorized human review only.</p><p>Temporary staging recordings include camera, microphone and interviewer audio. Do not use real candidate data before privacy, retention and media acceptance checks.</p></article></div></section>}
 </main></div>
 {LIVE&&<CareersDialogs {...{selected,setSelected,applyRole,setApplyRole,user,auth,busy,error,setError,begin,apply}}/>}
 <Dialogs {...{auth,setAuth,register,setRegister,selected:LIVE?null:selected,setSelected,applyRole:LIVE?null:applyRole,setApplyRole,user,report,setReport,practice,setPractice,help:false,setHelp,busy,error,setError,authenticate,apply,begin}}/>
 {help&&<div role="dialog" aria-modal="true" aria-label="Interview help" className="role-editor" style={{position:'fixed',inset:'15%',zIndex:60,overflow:'auto',boxShadow:'0 0 0 100vmax #241c3880'}}><Button variant="outline" onClick={()=>setHelp(false)}>Close help</Button><h2>Your interview, with you in control.</h2><p>New interviews begin with six shared questions and then four domain questions, with limited clarifying follow-ups. After one Begin action, the interviewer speaks and automatically listens. Pause and a typing alternative remain available.</p><p>Camera self-preview and audio/video recording are inside the interview, after explicit consent. Sarvam processes interview audio and text. PostgreSQL holds answers; ClickUp receives submitted transcripts and reports. Temporary server video copies can disappear—download important test copies.</p><p>Fictional staging data only. Authorized humans review evidence; no facial, emotion or honesty scoring is performed. Existing four-question applications stay on their previous flow.</p></div>}
 </div>;
}
