import test from 'node:test';import assert from 'node:assert/strict';import {InterviewMedia} from './interview-media.mjs';
const stopped=[];
function setup(){
 stopped.length=0;const audio={kind:'audio',stop(){stopped.push('audio');}},video={kind:'video',stop(){stopped.push('video');}};
 globalThis.MediaStream=class{constructor(tracks){this.tracks=tracks;}getTracks(){return this.tracks;}getAudioTracks(){return this.tracks.filter(t=>t.kind==='audio');}getVideoTracks(){return this.tracks.filter(t=>t.kind==='video');}};
 Object.defineProperty(globalThis,'navigator',{configurable:true,value:{mediaDevices:{getUserMedia:async()=>new MediaStream([audio,video])}}});
 const connections=[];
 globalThis.AudioContext=class{constructor(){this.state='running';this.destination={kind:'speaker'};}async resume(){}async close(){this.state='closed';}createMediaStreamDestination(){return {kind:'mix',stream:new MediaStream([audio])};}createMediaStreamSource(){return {connect(target){connections.push(target);}};}createAnalyser(){return {getFloatTimeDomainData(array){array.fill(0);}};}async decodeAudioData(){return {};}createBufferSource(){return {connect(target){connections.push(target);},start(){queueMicrotask(()=>this.onended?.());},stop(){}};}};
 globalThis.MediaRecorder=class{static isTypeSupported(){return true;}constructor(){this.state='inactive';}start(){this.state='recording';}stop(){this.state='inactive';this.ondataavailable?.({data:new Blob([new Uint8Array([26,69,223,163,1,2,3])])});this.onstop?.();}};
 return connections;
}
test('capture bound to application, mixes TTS and cleans up after finish',async()=>{const connections=setup(),calls=[];const media=new InterviewMedia({application:'app-a',call:async(path,body)=>{calls.push({path,body});return path==='/recordings'?{id:'r'}:{ready:true};},fetcher:async()=>({ok:true})});await media.start();await media.play(new Blob(['tts']));const result=await media.finish();assert.equal(calls[0].body.application_id,'app-a');assert.equal(calls[0].body.consent,'temporary-av-v1');assert.equal(result.error,null);assert.equal(calls.at(-1).path,'/recordings/r/finish');assert.equal(calls.at(-1).body.chunks,1);assert.ok(connections.some(x=>x.kind==='mix'));assert.ok(connections.some(x=>x.kind==='speaker'));assert.ok(stopped.includes('audio')&&stopped.includes('video'));await media.finish();assert.equal(calls.filter(x=>x.path.endsWith('/finish')).length,1);});
test('permission failure does not reserve a recording slot',async()=>{setup();navigator.mediaDevices.getUserMedia=async()=>{throw Error('denied');};let calls=0;const media=new InterviewMedia({application:'app-a',call:async()=>{calls++;}});await assert.rejects(media.start(),/denied/);assert.equal(calls,0);});
test('cancel while permission pending releases returned tracks',async()=>{setup();let release;const original=navigator.mediaDevices.getUserMedia;navigator.mediaDevices.getUserMedia=()=>new Promise(r=>release=r);const media=new InterviewMedia({application:'app-a',call:async()=>{throw Error('must not reserve');}});const pending=media.start();media.dispose();release(await original());await assert.rejects(pending,/cancelled/);assert.ok(stopped.includes('video'));});
