// Common public landing and pre-auth role selection; no recruiter signup.
import React,{useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,Button} from '@kits/shadcn-ui';
import {ArrowRight,UserRound,ShieldCheck} from 'lucide-react';
import {loginManually} from './login-client.mjs';
import {landingRequest,workspaceFor} from './landing-client.mjs';
import {publicRoles,display,workMode} from '../workspace/explore-jobs.mjs';
import PasswordField from './PasswordField';
import '../generated/styles.css';
import './landing.css';
function Brand(){return <a className="lp-brand" href="/" aria-label="Teamrecrut home"><span className="lp-mark" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 24 24">{[[2,7],[6,12],[10,17],[14,12],[18,7]].map(([x,h])=><rect key={x} x={x} y={(24-h)/2} width="2" height={h} rx="1" fill="currentColor"/>)}</svg></span><span>teamrecrut<small>BY STIRRING MINDS</small></span></a>;}
export default function PublicLanding(){
 const [roles,setRoles]=useState(null),[rolesError,setRolesError]=useState(''),[revision,setRevision]=useState(0),[selected,setSelected]=useState(null),[open,setOpen]=useState(false),[step,setStep]=useState('choice'),[role,setRole]=useState('candidate'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[identity,setIdentity]=useState(null);
 const mounted=useRef(false),lock=useRef(false),controller=useRef(null),form=useRef(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{const c=new AbortController();let active=true;setRoles(null);setRolesError('');landingRequest('/roles',{signal:c.signal}).then(publicRoles).then(r=>{if(active)setRoles(r);}).catch(e=>{if(active)setRolesError(e.message);});return()=>{active=false;c.abort();};},[revision]);
 // A signed-in user should never sit on the public landing: land them in their workspace.
 useEffect(()=>{const c=new AbortController();landingRequest('/me',{signal:c.signal}).then(u=>{if(u&&mounted.current)window.location.replace(workspaceFor(u));}).catch(()=>{});return()=>c.abort();},[]);
 async function work(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');controller.current=new AbortController();try{await fn(controller.current.signal);}catch(e){if(mounted.current)setError(e.message);}finally{lock.current=false;if(mounted.current)setBusy(false);}}
 function showAuth(){setSelected(null);setOpen(true);setStep('checking');return work(async signal=>{const u=await landingRequest('/me',{signal});if(!mounted.current)return;if(u){workspaceFor(u);setIdentity(u);setStep('existing');}else{setIdentity(null);setStep('choice');}});}
 function choose(value){if(busy)return;setRole(value);setStep('login');setError('');}
 function close(value){if(busy)return;setOpen(value);if(!value){form.current?.reset();setStep('choice');setIdentity(null);setError('');}}
 async function submit(e){e.preventDefault();const element=e.currentTarget,values=Object.fromEntries(new FormData(element)),signup=step==='signup';if(signup&&values.password!==values.confirm_password){setError('Passwords do not match.');return;}
  if(signup){const phone=String(values.phone||'').replace(/\s+/g,'');if(!/^\d{10}$/.test(phone)){setError('Phone number must be exactly 10 digits.');return;}values.phone=phone;}
  return work(async signal=>{
   // Recheck session before authenticating: choice cannot switch an existing account.
   const current=await landingRequest('/me',{signal});if(current){if(mounted.current){workspaceFor(current);setIdentity(current);setStep('existing');}return;}
   const u=signup?await landingRequest('/auth/candidate/signup',{body:values,signal}):await loginManually(role,values,{signal});
   const destination=workspaceFor(u);if(u.role!==(signup?'candidate':role))throw Error('The account type did not match. Please sign in again.');
   if(!mounted.current)return;element.reset();if(signup){setIdentity(u);setStep('setup');}else window.location.assign(destination);
  });
 }
 return <div className="lp-page"><a className="lp-skip" href="#lp-main">Skip to content</a><header className="lp-header"><Brand/><nav aria-label="Public navigation"><a href="#lp-about">About</a><a href="#lp-how">How it works</a><a href="#lp-roles">Open roles</a><button onClick={showAuth} disabled={busy}>Login / Sign up</button></nav></header>
 <main id="lp-main"><section className="lp-hero"><p className="lp-eyebrow">OPPORTUNITIES AT STIRRING MINDS</p><h1>Find your next<br/><span>opportunity.</span></h1><p>Explore roles and share your experience through an AI-assisted interview.</p><div className="lp-actions"><a className="lp-primary" href="#lp-roles">Explore open roles <ArrowRight size={18}/></a><button className="lp-secondary" onClick={showAuth} disabled={busy}>Login / Sign up</button></div><p className="lp-human">Your experience, in your words. People make the hiring decisions.</p></section>
 <section id="lp-about" className="lp-section"><p className="lp-eyebrow">ABOUT TEAMRECRUT</p><h2>A clearer place to start.</h2><p>Teamrecrut brings Stirring Minds opportunities, candidate profiles, applications and conversational interviews into one place.</p><p>Explore the published roles below, learn what each involves, and decide where you want to apply.</p></section>
 <section id="lp-how" className="lp-section"><h2>How it works</h2><div className="lp-steps">{[['Create your account','Choose Candidate and register or sign in.'],['Tell your story','Add your background, projects and a resume link in My Profile. You can complete this later.'],['Apply and interview','Apply to a role. Read the consent information and check your devices before Begin.'],['Human review','The hiring team reviews your application and interview evidence.']].map(([title,copy],i)=><article key={title}><span className="lp-step-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section id="lp-roles" className="lp-section"><div className="lp-section-header"><div><p className="lp-eyebrow">FIND YOUR FIT</p><h2>Open roles</h2></div></div>{!roles&&!rolesError&&<p role="status">Loading open roles…</p>}{rolesError&&<div role="alert"><p>{rolesError}</p><button onClick={()=>setRevision(n=>n+1)}>Try again</button></div>}{roles?.length===0&&<p>No open roles right now. Please check again later.</p>}<div className="lp-jobs">{roles?.map(r=><article key={r.id}><p className="lp-eyebrow">{display(r.department)}</p><h3>{r.title}</h3><p>{workMode(r)} · {display(r.type)}</p><p>{display(r.description)}</p><div className="lp-skills">{r.skills.map((s,i)=><span key={i}>{s}</span>)}</div><button onClick={()=>setSelected(r)}>View role <ArrowRight size={16}/></button></article>)}</div></section>
 <section className="lp-team lp-section"><div><h2>Stirring Minds hiring team</h2><p>Authorised recruiter access to manage roles and review interview evidence.</p></div><button onClick={showAuth} disabled={busy}>Access your workspace</button></section>
 <section className="lp-section lp-privacy"><h2>Before your interview</h2><p>Audio and video recording require explicit consent and device checks before Begin. Review the processing and storage information in the interview flow before starting.</p><p>Resume is currently an externally hosted HTTPS link inside My Profile; file upload is not available. Signing up does not guarantee selection or an offer.</p></section></main><footer className="lp-footer"><Brand/><p>Stirring Minds · Teamrecrut</p><a href="#lp-how">How it works</a></footer>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="lp-role-dialog"><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>Stirring Minds · {workMode(selected)} · {display(selected?.type)} · {display(selected?.experience)}</DialogDescription>{selected&&<><p>{display(selected.description)}</p><h3>What you’ll work on</h3><p className="lp-saved">{display(selected.details)}</p><div className="lp-skills">{selected.skills.map((s,i)=><span key={i}>{s}</span>)}</div><p>Apply from your candidate workspace. No recording starts here.</p><Button onClick={showAuth}>Continue to apply <ArrowRight/></Button></>}</DialogContent></Dialog>
 <Dialog open={open} onOpenChange={close}><DialogContent className="lp-auth-dialog" onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onInteractOutside={e=>{if(busy)e.preventDefault();}}><DialogTitle>{step==='choice'?'How would you like to continue?':step==='signup'?'Create your candidate account':step==='setup'?'Your account is ready':step==='existing'?'Continue to your workspace':step==='checking'?'Checking your session…':role==='recruiter'?'Recruiter sign in':'Welcome back'}</DialogTitle><DialogDescription>{step==='choice'?'Choose the account type you want to sign in to.':step==='signup'?'Create an account to explore Stirring Minds opportunities.':step==='setup'?'Add profile details now or go straight to your dashboard.':step==='existing'?'You are already signed in. Your existing account determines your access.':role==='recruiter'?'Authorised Stirring Minds hiring access.':'Sign in to continue your job search.'}</DialogDescription>
 {step==='choice'&&<div className="lp-role-choice"><button onClick={()=>choose('candidate')}><UserRound/><strong>Candidate</strong><span>Explore jobs, apply and complete interviews.</span><b>Continue as Candidate →</b></button><button onClick={()=>choose('recruiter')}><ShieldCheck/><strong>Recruiter</strong><span>Authorised Stirring Minds hiring access.</span><b>Continue as Recruiter →</b></button></div>}
 {['login','signup'].includes(step)&&<><button className="lp-back" disabled={busy} onClick={()=>{form.current?.reset();setStep('choice');setError('');}}>← Back to account selection</button><form ref={form} key={role+step} onSubmit={submit} aria-busy={busy}>{step==='signup'&&<label>Full name<input name="name" autoComplete="name" required minLength={2} maxLength={100} disabled={busy}/></label>}<label>{role==='recruiter'?'Work email':'Email address'}<input name="email" type="email" autoComplete="username" required maxLength={254} disabled={busy}/></label><label>Password<PasswordField name="password" autoComplete={step==='signup'?'new-password':'current-password'} disabled={busy}/></label>{step==='signup'&&<><label>Confirm password<PasswordField name="confirm_password" autoComplete="new-password" disabled={busy}/></label><label>Phone number<input name="phone" type="tel" inputMode="numeric" pattern="\d{10}" required maxLength={10} autoComplete="tel" disabled={busy} placeholder="10-digit mobile number"/></label></>}<Button type="submit" disabled={busy}>{busy?'Please wait…':step==='signup'?'Create candidate account':'Sign in'}</Button></form>{role==='candidate'&&<button className="lp-back" disabled={busy} onClick={()=>{setStep(step==='signup'?'login':'signup');setError('');}}>{step==='signup'?'Already have an account? Sign in':'Create candidate account'}</button>}{role==='candidate'&&<p className="lp-note">Google sign-in is available only when verified configuration is enabled on the <a href="/candidate/login">dedicated candidate login page</a>.</p>}{role==='recruiter'&&<p className="lp-note">Manual sign-in only. No public recruiter registration.</p>}<p className="lp-note">Password recovery email setup is pending; reset emails cannot be requested here yet.</p></>}
 {step==='setup'&&<div className="lp-setup"><a className="lp-primary" href="/candidate/workspace/profile">Complete My Profile</a><a className="lp-secondary" href="/candidate/workspace/dashboard">Go to dashboard</a><p>Resume links, skills and preferences can be added later inside My Profile.</p></div>}
 {step==='existing'&&identity&&<a className="lp-primary" href={workspaceFor(identity)}>Open my workspace →</a>}{error&&<div role="alert"><p>{error}</p>{step==='checking'&&<button disabled={busy} onClick={showAuth}>Try again</button>}</div>}
 </DialogContent></Dialog></div>;
}
