import assert from 'node:assert/strict';
export async function checkCandidateAccount(browser){
 const c=await browser.newContext({viewport:{width:1440,height:1000}});
 try{const p=await c.newPage();p.setDefaultTimeout(15000);let user={role:'candidate',admin:false,name:'Test'},google=false,fail=false,tickets=[],posts=0;
 await p.route('**/api/me',r=>r.fulfill({json:user}));
 await p.route('**/api/workspace/candidate/account',r=>r.fulfill({json:{email:'test@example.com',role:'candidate',auth_method:google?'google':'password',password_change_allowed:!google}}));
 await p.route('**/api/workspace/password',r=>r.fulfill({status:401,json:{error:'wrong'}}));
 await p.route('**/api/workspace/support',r=>{if(r.request().method()==='POST'){posts++;if(fail)return r.fulfill({status:500,json:{error:'private'}});const b=r.request().postDataJSON();tickets=[{id:'ticket',...b,reply:'',status:'open',created:'2026-09-14T06:00:00Z'}];return r.fulfill({json:{id:'ticket',status:'open'}});}return r.fulfill(fail?{status:500,json:{error:'private'}}:{json:tickets});});
 const go=page=>p.goto('http://127.0.0.1:8765/candidate/workspace/'+page);
 await go('settings');await p.getByRole('heading',{name:'Account details',exact:true}).waitFor();assert(await p.getByLabel('Login email',{exact:true}).getAttribute('readonly')!==null);assert.equal(await p.locator('a[href*="recruiter"]').count(),0);
 await p.getByLabel('Current password',{exact:true}).fill('synthetic-old');await p.getByLabel('New password',{exact:true}).fill('synthetic-new-password');await p.getByLabel('Confirm new password',{exact:true}).fill('different-password');await p.getByRole('button',{name:'Change password and sign out',exact:true}).click();await p.getByText('New passwords do not match.',{exact:true}).waitFor();await p.getByLabel('Confirm new password',{exact:true}).fill('synthetic-new-password');await p.getByRole('button',{name:'Change password and sign out',exact:true}).click();await p.getByText('Current password was not accepted, or your session expired.',{exact:true}).waitFor();assert.equal(await p.getByLabel('New password',{exact:true}).inputValue(),'synthetic-new-password');
 google=true;await go('settings');await p.getByText('This account uses Google sign-in. Manage your Google password through Google.',{exact:true}).waitFor();assert.equal(await p.getByLabel('Current password',{exact:true}).count(),0);
 await go('help');await p.getByText('No support requests yet.',{exact:true}).waitFor();await p.getByLabel('Subject',{exact:true}).fill('Synthetic issue');await p.getByLabel('Message',{exact:true}).fill('Synthetic support details for testing.');fail=true;await p.getByRole('button',{name:'Send in-app request',exact:true}).click();await p.getByText('Request failed. Your unsaved input has been kept.',{exact:true}).waitFor();assert.equal(await p.getByLabel('Subject',{exact:true}).inputValue(),'Synthetic issue');fail=false;await p.getByRole('button',{name:'Send in-app request',exact:true}).click();await p.getByText('Request saved in your in-app support inbox. No email was sent.',{exact:true}).waitFor();await p.getByRole('heading',{name:'Synthetic issue',exact:true}).waitFor();assert.equal(posts,2);assert.equal(await p.getByLabel('Subject',{exact:true}).inputValue(),'');
 tickets[0].reply='Synthetic team reply';await p.getByRole('button',{name:'Refresh inbox',exact:true}).click();await p.getByText('Synthetic team reply',{exact:true}).waitFor();
 for(const w of [390,320]){await p.setViewportSize({width:w,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 user={role:'recruiter',admin:true};await go('help');await p.getByRole('heading',{name:'Candidate access required',exact:true}).waitFor();
 console.log('::notice title=Candidate Settings and Support::PASS: manual/Google display, read-only identity, password validation/failure retention, support create/retry/read/reply, candidate denial and mobile fit. Mock transport; WSGI tests cover persistence and session revocation.');
 }finally{await c.close();}
}
