import assert from 'node:assert/strict';
export async function checkPublicLanding(browser){
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 try{
  const p=await context.newPage();p.setDefaultTimeout(15000);let user=null,fail=false,empty=false,signup=0,login=0;
  await p.route('**/api/me',r=>r.fulfill({json:user}));
  await p.route('**/api/roles',r=>r.fulfill(fail?{status:500,json:{error:'private'}}:{json:empty?[]:[{id:'real-row',title:'Synthetic saved role',department:'IT',description:'From synthetic API, not hard-coded UI.',details:'First line\nSecond line',location:'Remote',type:'Full-time',experience:'0-2',skills:['Python'],notes:'DO-NOT-SHOW'}]}));
  await p.route('**/api/auth/candidate/signup',r=>{signup++;assert.equal(r.request().method(),'POST');assert(!('role' in r.request().postDataJSON()));return r.fulfill({json:{role:'candidate',admin:false,name:'Synthetic'}});});
  await p.route('**/api/auth/recruiter/login',r=>{login++;return r.fulfill({status:401,json:{error:'bad'}});});
  const open=()=>p.getByRole('navigation',{name:'Public navigation'}).getByRole('button',{name:'Login / Sign up',exact:true}).click();
  await p.goto('http://127.0.0.1:8765/');await p.getByRole('heading',{name:'Synthetic saved role',exact:true}).waitFor();assert(!(await p.locator('body').innerText()).includes('DO-NOT-SHOW'));
  for(const w of [390,320]){await p.setViewportSize({width:w,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  await open();let modal=p.getByRole('dialog');await modal.getByRole('button',{name:/Continue as Recruiter/}).click();await modal.getByLabel('Work email',{exact:true}).fill('team@stirringminds.com');await modal.getByLabel('Password',{exact:true}).fill('synthetic-password-long');await modal.getByRole('button',{name:'Sign in',exact:true}).click();await modal.getByRole('alert').waitFor();assert.equal(login,1);assert.equal(await modal.getByRole('button',{name:'Create candidate account',exact:true}).count(),0);assert.equal(await modal.locator('a[href*="google"]').count(),0);
  await modal.getByRole('button',{name:'Back to account selection',exact:false}).click();await modal.getByRole('button',{name:/Continue as Candidate/}).click();await modal.getByRole('button',{name:'Create candidate account',exact:true}).click();await modal.getByLabel('Full name',{exact:true}).fill('Synthetic Candidate');await modal.getByLabel('Email address',{exact:true}).fill('synthetic@example.com');await modal.getByLabel('Password',{exact:true}).fill('synthetic-password-long');await modal.getByLabel('Confirm password',{exact:true}).fill('wrong-password-long');await modal.getByRole('button',{name:'Create candidate account',exact:true}).click();await modal.getByText('Passwords do not match.',{exact:true}).waitFor();assert.equal(signup,0);
  await modal.getByLabel('Confirm password',{exact:true}).fill('synthetic-password-long');await modal.getByRole('button',{name:'Create candidate account',exact:true}).click();await modal.getByRole('heading',{name:'Your account is ready',exact:true}).waitFor();assert.equal(signup,1);assert.equal(await modal.getByRole('link',{name:'Go to dashboard'}).getAttribute('href'),'/candidate/workspace/dashboard');assert.equal(await modal.getByRole('link',{name:'Complete My Profile'}).getAttribute('href'),'/candidate/workspace/profile');
  await p.keyboard.press('Escape');user={role:'candidate',admin:false};await open();await modal.getByRole('heading',{name:'Continue to your workspace',exact:true}).waitFor();assert.equal(await modal.getByRole('button',{name:/Continue as Recruiter/}).count(),0);assert.equal(await modal.getByRole('link',{name:'Open my workspace →'}).getAttribute('href'),'/candidate/workspace/dashboard');await p.keyboard.press('Escape');
  fail=true;await p.getByRole('button',{name:'Refresh roles',exact:true}).click();await p.getByRole('alert').waitFor();fail=false;empty=true;await p.getByRole('button',{name:'Try again',exact:true}).click();await p.getByText('No open roles right now. Please check again later.',{exact:true}).waitFor();
  console.log('::notice title=Public landing acceptance::PASS: saved public roles, mobile fit, popup role separation, failed recruiter login, candidate signup/password confirmation, optional profile/dashboard choice, existing-session guard, role loading error/retry/empty. Mock auth boundaries, not live provider tests.');
 }finally{await context.close();}
}
